# Introduction to Pandas

Pandas is a package built on top of numpy which incorporates many additional features which make it more convenient for data analysis. One main addition is the inclusion of row and column labels, which make pandas function much like spreadsheet software. It also includes tools for much more complex computations than regular numpy allows

In [36]:
import pandas as pd
import numpy as np
# by default, pandas only shows the beginning and end of a large dataframe
# You can choose how many rows and columns to show.
# If you want to see all of the rows, set the respective value to None
pd.options.display.max_rows = 100 
pd.options.display.max_columns = 50

## Importing data
There are a lot of built-in functions for importing data to pandas, for example, from files, database, and web sources. For a full list of the supported methods, see [the documentation on pandas](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html).

In this example, we're going to load data formatted as a csv from a website URL. In particular, it is a direct link to a file hosted in our course github repository.

The data we're loading is a simplified pokedex which includes the number, name, base stats, types, abilities, and colors of each pokemon. We'll be using this data to explore the functionality of pandas. 

The primary class of pandas is the DataFrame, which functions like a spreadsheet (like in excel). It allows for named rows and columns. Data types between two different columns can vary, but entries within the same column should have the same type.

In [37]:
# URL for data hosted online
pokedex_url = 'https://raw.githubusercontent.com/bwsi-remote-sensing-2020/01-Intro-to-python/master/pokedex.csv' 

pokedex_df = pd.read_csv(pokedex_url, index_col='Index') # create a dataframe from a csv, set the column titled "Index" as the row labels

In [38]:
# in our case, the cloned repository includes the pokedex file in the folder, 
# so we could equivalently use the filename instead of a URL
pokedex_df = pd.read_csv('pokedex.csv', index_col='Index')

In [39]:
# We'll do some cleanup to deal with empty values
pokedex_df = pokedex_df.fillna('') # fill in the NaN values with empty string 

pokedex_df # prints out the dataframe

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Index,,,,,,,,,,,,,,
1.0,Bulbasaur,45,49,49,65,65,45,318,Grass,Poison,Overgrow,,Chlorophyll,Green
2.0,Ivysaur,60,62,63,80,80,60,405,Grass,Poison,Overgrow,,Chlorophyll,Green
3.0,Venusaur,80,82,83,100,100,80,525,Grass,Poison,Overgrow,,Chlorophyll,Green
4.0,Charmander,39,52,43,60,50,65,309,Fire,,Blaze,,Solar Power,Red
5.0,Charmeleon,58,64,58,80,65,80,405,Fire,,Blaze,,Solar Power,Red
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
798.0,Kartana,59,181,131,59,31,109,570,Grass,Steel,Beast Boost,,,White
799.0,Guzzlord,223,101,53,97,53,43,570,Dark,Dragon,Beast Boost,,,Black
800.0,Necrozma,97,107,101,127,89,79,600,Psychic,,Prism Armor,,,Black
801.0,Magearna,80,95,115,130,115,65,600,Steel,Fairy,Soul-Heart,,,Gray
802.0,Marshadow,90,125,80,90,90,125,600,Fighting,Ghost,Technician,,,Gray

## Indexing
Like numpy, you can index a dataframe to select elements or subsets of entries. There are a number of ways to index pandas dataframes. The two following methods are recommended:
`.loc[]` and `.iloc[]`

### .loc[ ] name-based indexing
The first way, using `.loc[a,b]` indexes based on the __values__ of the row index and column names. This allows us to get entries where the row index value equals `a` and the column name equals `b`.

In [40]:
# Get the entry for index value 745.1 - Lycanroc (midnight)
pokedex_df.loc[745.1]

Pokemon           Lycanroc (midnight)
HP                                 85
Atk                               115
Def                                75
SpAtk                              55
SpDef                              75
Speed                              82
Total                             487
Type I                           Rock
Type II
Ability I                    Keen Eye
Ability II              Vital Spirit
Hidden Ability               No Guard
Color                           Brown
Name: 745.1, dtype: object

In [41]:
# You can get specific column values for a single entry
pokedex_df.loc[250,['Pokemon','Type I','Type II']]

Pokemon    Swinub
Type I        Ice
Type II    Ground
Name: 250.0, dtype: object

In [42]:
# you can use the : notation to slice multiple rows and columns
pokedex_df.loc[690:700,'Pokemon':'Total']

          Pokemon   HP  Atk  Def  SpAtk  SpDef  Speed  Total
Index
690.0      Skrelp   50   60   60     60     60     30    320
691.0    Dragalge   65   75   90     97    123     44    494
692.0   Clauncher   50   53   62     58     63     44    330
693.0   Clawitzer   71   73   88    120     89     59    500
694.0  Helioptile   44   38   33     61     43     70    289
695.0   Heliolisk   62   55   52    109     94    109    481
696.0      Tyrunt   58   89   77     45     45     48    362
697.0   Tyrantrum   82  121  119     69     59     71    521
698.0      Amaura   77   59   50     67     63     46    362
699.0     Aurorus  123   77   72     99     92     58    521
700.0     Sylveon   95   65   65    110    130     60    525

In [43]:
# Similarly to numpy, you can use the : notation without indices on a side to mean "from beginning" or "to end"
pokedex_df.loc[:10,"Ability I":]

         Ability I Ability II Hidden Ability  Color
Index
1.0       Overgrow               Chlorophyll  Green
2.0       Overgrow               Chlorophyll  Green
3.0       Overgrow               Chlorophyll  Green
4.0          Blaze               Solar Power    Red
5.0          Blaze               Solar Power    Red
6.0          Blaze               Solar Power    Red
7.0        Torrent                 Rain Dish   Blue
8.0        Torrent                 Rain Dish   Blue
9.0        Torrent                 Rain Dish   Blue
10.0   Shield Dust                  Run Away  Green

In [44]:
# and : by itself gives all of the entries in that dimension
pokedex_df.loc[:,'Pokemon'].head(10) #just return top 10 entries

Index
1.0      Bulbasaur
2.0        Ivysaur
3.0       Venusaur
4.0     Charmander
5.0     Charmeleon
6.0      Charizard
7.0       Squirtle
8.0      Wartortle
9.0      Blastoise
10.0      Caterpie
Name: Pokemon, dtype: object

### .iloc[ ] integer indexing

The second way, using `.iloc[i,j]` uses the numpy-style integer indices to get a value. In this case, iloc takes integer values from 0 to the number of entries in that dimension. 

Like numpy, `.iloc[i,j]` gives the entry at the $i^{th}$ row and $j^{th}$ column.

In [45]:
pokedex_df.iloc[100] # gets 101st row (recall python counts from 0)

Pokemon            Electrode
HP                        60
Atk                       50
Def                       70
SpAtk                     80
SpDef                     80
Speed                    140
Total                    480
Type I              Electric
Type II
Ability I         Soundproof
Ability II            Static
Hidden Ability     Aftermath
Color                    Red
Name: 110.0, dtype: object

In [46]:
# The : style indexing also works for iloc
pokedex_df.iloc[25:30, 0:8]

         Pokemon  HP  Atk  Def  SpAtk  SpDef  Speed  Total
Index
27.0      Raichu  60   90   55     90     80    100    475
28.0   Sandshrew  50   75   85     20     30     40    300
29.0   Sandslash  75  100  110     45     55     65    450
30.0    Nidoran♀  55   47   52     40     40     41    275
31.0    Nidorina  70   62   67     55     55     56    365

## Changing index column
You can change the index column of the dataframe with `.set_index()` or reset it to default numerical indexing with `.reset_index()`.

Note however, that these operations create a __copy__ of the original dataframe, and do not change the dataframe "in place" (i.e. doesn't change the original object)

In [47]:
# reset index to be default numerical index
reindexed_pokedex = pokedex_df.reset_index()
reindexed_pokedex.head()

,Index,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
0,1.0,Bulbasaur,45,49,49,65,65,45,318,Grass,Poison,Overgrow,,Chlorophyll,Green
1,2.0,Ivysaur,60,62,63,80,80,60,405,Grass,Poison,Overgrow,,Chlorophyll,Green
2,3.0,Venusaur,80,82,83,100,100,80,525,Grass,Poison,Overgrow,,Chlorophyll,Green
3,4.0,Charmander,39,52,43,60,50,65,309,Fire,,Blaze,,Solar Power,Red
4,5.0,Charmeleon,58,64,58,80,65,80,405,Fire,,Blaze,,Solar Power,Red

In [48]:
# Change the index to the Pokemon name column
pokedex_indexed_by_name = pokedex_df.reset_index().set_index('Pokemon')
pokedex_indexed_by_name

,Index,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Pokemon,,,,,,,,,,,,,,
Bulbasaur,1.0,45,49,49,65,65,45,318,Grass,Poison,Overgrow,,Chlorophyll,Green
Ivysaur,2.0,60,62,63,80,80,60,405,Grass,Poison,Overgrow,,Chlorophyll,Green
Venusaur,3.0,80,82,83,100,100,80,525,Grass,Poison,Overgrow,,Chlorophyll,Green
Charmander,4.0,39,52,43,60,50,65,309,Fire,,Blaze,,Solar Power,Red
Charmeleon,5.0,58,64,58,80,65,80,405,Fire,,Blaze,,Solar Power,Red
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kartana,798.0,59,181,131,59,31,109,570,Grass,Steel,Beast Boost,,,White
Guzzlord,799.0,223,101,53,97,53,43,570,Dark,Dragon,Beast Boost,,,Black
Necrozma,800.0,97,107,101,127,89,79,600,Psychic,,Prism Armor,,,Black
Magearna,801.0,80,95,115,130,115,65,600,Steel,Fairy,Soul-Heart,,,Gray
Marshadow,802.0,90,125,80,90,90,125,600,Fighting,Ghost,Technician,,,Gray

In [49]:
# note that the original dataframe was not affected
pokedex_df
pokedex_indexed_by_name.loc['Charizard']

Index                       6
HP                         78
Atk                        84
Def                        78
SpAtk                     109
SpDef                      85
Speed                     100
Total                     534
Type I                   Fire
Type II                Flying
Ability I               Blaze
Ability II
Hidden Ability    Solar Power
Color                     Red
Name: Charizard, dtype: object

## Logical indexing
You can test conditionals on a column, for example, testing if the value of the column is greater than a value. What's returned is a boolean column of the same size, with a value of `True` wherever it is true, and `False` otherwise. (This can similarly be done in numpy).

In [50]:
pokedex_df['Total'] > 520

Index
1.0      False
2.0      False
3.0       True
4.0      False
5.0      False
         ...
798.0     True
799.0     True
800.0     True
801.0     True
802.0     True
Name: Total, Length: 820, dtype: bool

If you take that boolean column and use it to index the dataframe, you can get all of the entries that satisfy that condition.

In [51]:
pokedex_df.loc[pokedex_df['Total']>=520] # all of the pokemon with total base stats greater than 500

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Index,,,,,,,,,,,,,,
3.0,Venusaur,80,82,83,100,100,80,525,Grass,Poison,Overgrow,,Chlorophyll,Green
6.0,Charizard,78,84,78,109,85,100,534,Fire,Flying,Blaze,,Solar Power,Red
9.0,Blastoise,79,83,100,85,105,78,530,Water,,Torrent,,Rain Dish,Blue
64.0,Arcanine,90,110,80,100,80,95,555,Fire,,Intimidate,Flash Fire,Justified,Brown
99.0,Cloyster,50,90,180,85,45,70,520,Water,Ice,Shell Armor,Skill Link,Overcoat,Purple
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
798.0,Kartana,59,181,131,59,31,109,570,Grass,Steel,Beast Boost,,,White
799.0,Guzzlord,223,101,53,97,53,43,570,Dark,Dragon,Beast Boost,,,Black
800.0,Necrozma,97,107,101,127,89,79,600,Psychic,,Prism Armor,,,Black
801.0,Magearna,80,95,115,130,115,65,600,Steel,Fairy,Soul-Heart,,,Gray
802.0,Marshadow,90,125,80,90,90,125,600,Fighting,Ghost,Technician,,,Gray

In [52]:
# Get all of the pokemon of a given color
pokedex_df.loc[pokedex_df['Color']=='Black']

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Index,,,,,,,,,,,,,,
174.0,Snorlax,160,110,65,65,110,30,540,Normal,,Immunity,Thick Fat,Gluttony,Black
162.0,Umbreon,95,65,110,60,130,65,525,Dark,,Synchronize,,Inner Focus,Black
226.0,Murkrow,60,85,42,85,42,91,405,Dark,Flying,Insomnia,Super Luck,Prankster,Black
230.0,Unown,48,72,48,72,48,48,336,Psychic,,Levitate,,,Black
244.0,Sneasel,55,95,55,35,75,115,430,Dark,Ice,Inner Focus,Keen Eye,Pickpocket,Black
260.0,Houndour,45,60,30,80,50,65,330,Dark,Fire,Early Bird,Flash Fire,Unnerve,Black
261.0,Houndoom,75,90,50,110,80,95,500,Dark,Fire,Early Bird,Flash Fire,Unnerve,Black
328.0,Mawile,50,85,85,55,55,50,380,Steel,Fairy,Hyper Cutter,Intimidate,Sheer Force,Black
352.0,Spoink,60,25,35,70,80,60,330,Psychic,,Thick Fat,Own Tempo,Gluttony,Black
363.0,Seviper,73,100,60,100,60,65,458,Poison,,Shed Skin,,Infiltrator,Black
371.0,Claydol,60,70,105,70,120,75,500,Ground,Psychic,Levitate,,,Black
380.0,Shuppet,44,75,35,63,33,45,295,Ghost,,Insomnia,Frisk,Cursed Body,Black
381.0,Banette,64,115,65,83,63,65,455,Ghost,,Insomnia,Frisk,Cursed Body,Black
382.0,Duskull,20,40,90,30,90,25,295,Ghost,,Levitate,,,Black
383.0,Dusclops,40,70,130,60,130,25,455,Ghost,,Pressure,,,Black
227.0,Honchkrow,100,125,52,105,52,71,505,Dark,Flying,Insomnia,Super Luck,Moxie,Black
461.0,Chatot,76,65,45,92,42,91,411,Normal,Flying,Keen Eye,Tangled Feet,Big Pecks,Black
173.0,Munchlax,135,85,40,40,85,5,390,Normal,,Pickup,Thick Fat,Gluttony,Black
245.0,Weavile,70,120,65,45,85,125,510,Dark,Ice,Pressure,,Pickpocket,Black
384.0,Dusknoir,45,100,135,65,135,45,525,Ghost,,Pressure,,,Black
487.0,Giratina,150,100,120,100,120,90,680,Ghost,Dragon,Pressure,,Telepathy,Black
487.1,Giratina (O),150,120,100,120,100,90,680,Ghost,Dragon,Levitate,,,Black
491.0,Darkrai,70,90,90,135,90,125,600,Dark,,Bad Dreams,,,Black
522.0,Blitzle,45,60,32,50,32,76,295,Electric,,Lightningrod,Motor Drive,Sap Sipper,Black
523.0,Zebstrika,75,100,63,80,63,116,497,Electric,,Lightningrod,Motor Drive,Sap Sipper,Black
561.0,Sigilyph,72,58,80,103,80,97,490,Psychic,Flying,Wonder Skin,Magic Guard,Tinted Lens,Black
562.0,Yamask,38,30,85,55,65,30,303,Ghost,,Mummy,,,Black
608.0,Lampent,60,40,60,95,60,55,370,Ghost,Fire,Flash Fire,Flame Body,Shadow Tag,Black
609.0,Chandelure,60,55,90,145,90,80,520,Ghost,Fire,Flash Fire,Flame Body,Shadow Tag,Black
644.0,Zekrom,100,150,120,120,100,90,680,Dragon,Electric,Teravolt,,,Black
664.0,Scatterbug,38,35,40,27,25,35,200,Bug,,Shield Dust,Compound Eyes,Friend Guard,Black
665.0,Spewpa,45,22,60,27,30,29,213,Bug,,Shed Skin,,Friend Guard,Black
666.0,Vivillon,80,52,50,90,50,89,411,Bug,Flying,Shield Dust,Compound Eyes,Friend Guard,Black
731.0,Pikipek,35,75,30,30,30,65,265,Normal,Flying,Keen Eye,Skill Link,Pickup,Black
732.0,Trumbeak,55,85,50,40,50,75,355,Normal,Flying,Keen Eye,Skill Link,Pickup,Black
733.0,Toucannon,80,120,75,75,75,60,485,Normal,Flying,Keen Eye,Skill Link,Sheer Force,Black
757.0,Salandit,48,44,40,71,40,77,320,Poison,Fire,Corrosion,Oblivious,Oblivious,Black
758.0,Salazzle,68,64,60,111,60,117,480,Poison,Fire,Corrosion,Oblivious,Oblivious,Black
771.0,Pyukumuku,55,60,130,30,130,5,410,Water,,Innards Out,Unaware,Unaware,Black
796.0,Xurkitree,83,89,71,173,71,83,570,Electric,,Beast Boost,,,Black
799.0,Guzzlord,223,101,53,97,53,43,570,Dark,Dragon,Beast Boost,,,Black
800.0,Necrozma,97,107,101,127,89,79,600,Psychic,,Prism Armor,,,Black

### Compound boolean queries
You can use boolean operations (OR, AND, NOT) to combine conditions

We will look for pokemon with specific types to demonstrate compound queries

### OR queries
In the following example, we query for all pokemon who have at least part "Dragon" typing.

The vertical line | represents the element-wise "OR" operation. "OR" operations require either or both statements on either side of the operation to be true.

Thus, the below query 

```query = (pokedex_df['Type I']=='Dragon') | (pokedex_df['Type II']=='Dragon')```

asks, for each row, if 'Type I' is equal to "Dragon" OR 'Type II' is equal to "Dragon"

In [74]:
query = (pokedex_df['Type I']=='Dragon') | (pokedex_df['Type II']=='Dragon')
pokedex_df.loc[query] # Get all of the entries corresponding to the above query

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color,Nickname
Index,,,,,,,,,,,,,,,
178.0,Dratini,41,64,45,50,50,50,300,Dragon,,Shed Skin,,Marvel Scale,Blue,None
179.0,Dragonair,61,84,65,70,70,70,420,Dragon,,Shed Skin,,Marvel Scale,Blue,None
180.0,Dragonite,91,134,95,100,100,80,600,Dragon,Flying,Inner Focus,,Multiscale,Brown,None
134.0,Kingdra,75,95,95,95,95,85,540,Water,Dragon,Swift Swim,Sniper,Damp,Blue,None
356.0,Vibrava,50,70,50,50,50,70,340,Ground,Dragon,Levitate,,,Green,None
357.0,Flygon,80,100,80,80,80,100,520,Ground,Dragon,Levitate,,,Green,None
361.0,Altaria,75,70,90,70,105,80,490,Dragon,Flying,Natural Cure,,Cloud Nine,Blue,None
400.0,Bagon,45,75,60,40,30,50,300,Dragon,,Rock Head,,Sheer Force,Blue,None
401.0,Shelgon,65,95,100,60,50,50,420,Dragon,,Rock Head,,Overcoat,White,None
402.0,Salamence,95,135,80,110,80,100,600,Dragon,Flying,Intimidate,,Moxie,Blue,None
409.0,Latias,80,80,90,110,130,110,600,Dragon,Psychic,Levitate,,,Red,None
410.0,Latios,80,90,80,130,110,110,600,Dragon,Psychic,Levitate,,,Blue,None
413.0,Rayquaza,105,150,90,150,90,95,680,Dragon,Flying,Air Lock,,,Green,None
463.0,Gible,58,70,45,40,45,42,300,Dragon,Ground,Sand Veil,,Rough Skin,Blue,None
464.0,Gabite,68,90,65,50,55,82,410,Dragon,Ground,Sand Veil,,Rough Skin,Blue,None
465.0,Garchomp,108,130,95,80,85,102,600,Dragon,Ground,Sand Veil,,Rough Skin,Blue,None
483.0,Dialga,100,120,120,150,100,90,680,Steel,Dragon,Pressure,,Telepathy,White,None
484.0,Palkia,90,120,100,150,120,100,680,Water,Dragon,Pressure,,Telepathy,Purple,None
487.0,Giratina,150,100,120,100,120,90,680,Ghost,Dragon,Pressure,,Telepathy,Black,None
487.1,Giratina (O),150,120,100,120,100,90,680,Ghost,Dragon,Levitate,,,Black,None
610.0,Axew,46,87,60,30,40,57,320,Dragon,,Rivalry,Mold Breaker,Unnerve,Green,None
611.0,Fraxure,66,117,70,40,50,67,410,Dragon,,Rivalry,Mold Breaker,Unnerve,Green,None
612.0,Haxorus,76,147,90,60,70,97,540,Dragon,,Rivalry,Mold Breaker,Unnerve,Yellow,None
621.0,Druddigon,77,120,90,60,90,48,485,Dragon,,Rough Skin,Sheer Force,Mold Breaker,Red,None
633.0,Deino,52,65,50,45,50,38,300,Dark,Dragon,Hustle,,,Blue,None
634.0,Zweilous,72,85,70,65,70,58,420,Dark,Dragon,Hustle,,,Blue,None
635.0,Hydreigon,92,105,90,125,90,98,600,Dark,Dragon,Levitate,,,Blue,None
643.0,Reshiram,100,120,100,150,120,90,680,Dragon,Fire,Turboblaze,,,White,None
644.0,Zekrom,100,150,120,120,100,90,680,Dragon,Electric,Teravolt,,,Black,None
646.0,Kyurem,125,130,90,130,90,95,660,Dragon,Ice,Pressure,,,Gray,None
691.0,Dragalge,65,75,90,97,123,44,494,Poison,Dragon,Poison Point,Poison Touch,Adaptability,Brown,None
696.0,Tyrunt,58,89,77,45,45,48,362,Rock,Dragon,Strong Jaw,,Sturdy,Brown,None
697.0,Tyrantrum,82,121,119,69,59,71,521,Rock,Dragon,Strong Jaw,,Sturdy,Red,None
704.0,Goomy,45,50,35,55,75,40,300,Dragon,,Sap Sipper,Hydration,Gooey,Purple,None
705.0,Sliggoo,68,75,53,83,113,60,452,Dragon,,Sap Sipper,Hydration,Gooey,Purple,None
706.0,Goodra,90,100,70,110,150,80,600,Dragon,,Sap Sipper,Hydration,Gooey,Purple,None
714.0,Noibat,40,30,35,45,40,55,245,Flying,Dragon,Frisk,Infiltrator,Telepathy,Purple,None
715.0,Noivern,85,70,80,97,80,123,535,Flying,Dragon,Frisk,Infiltrator,Telepathy,Purple,None
718.0,Zygarde,108,100,121,81,95,95,600,Dragon,Ground,Aura Break,,,Green,None
776.0,Turtonator,60,78,135,91,85,36,485,Fire,Dragon,Shell Armor,,,Red,None
780.0,Drampa,78,60,85,135,91,36,485,Normal,Dragon,Berserk,Sap Sipper,Cloud Nine,White,None
782.0,Jangmo-o,45,55,65,45,45,45,300,Dragon,,Bulletproof,Soundproof,Overcoat,Gray,None
783.0,Hakamo-o,55,75,90,65,70,65,420,Dragon,Fighting,Bulletproof,Soundproof,Overcoat,Gray,None
784.0,Kommo-o,75,110,125,100,105,85,600,Dragon,Fighting,Bulletproof,Soundproof,Overcoat,Gray,None
799.0,Guzzlord,223,101,53,97,53,43,570,Dark,Dragon,Beast Boost,,,Black,None

In [54]:
(pokedex_df['Type I']=='Dragon').all()

False

### AND queries
The ampersand `&` character represents the element-wise boolean operation "AND". In order for an "AND" statement to be true, both conditions on either side of the operation must be true.

We can combine boolean operations to construct complex queries: for example, getting all pokemon who are both Dragon and Flying types. The query below looks for pokemon who are EITHER (Primary Type "Flying" AND Secondary Type "Dragon") OR (Primary Type "Dragon" AND Secondary Type "Flying")

Note that parentheses should be used to group operations so that the order of operations is clear

In [73]:
# you can use the backslash operator \ to continue code on the next line
query = ((pokedex_df['Type I']=='Flying') & (pokedex_df['Type II']=='Dragon'))\
        | ((pokedex_df['Type I']=='Dragon') & (pokedex_df['Type II']=='Flying'))
pokedex_df.loc[query]

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color,Nickname
Index,,,,,,,,,,,,,,,
180.0,Dragonite,91,134,95,100,100,80,600,Dragon,Flying,Inner Focus,,Multiscale,Brown,None
361.0,Altaria,75,70,90,70,105,80,490,Dragon,Flying,Natural Cure,,Cloud Nine,Blue,None
402.0,Salamence,95,135,80,110,80,100,600,Dragon,Flying,Intimidate,,Moxie,Blue,None
413.0,Rayquaza,105,150,90,150,90,95,680,Dragon,Flying,Air Lock,,,Green,None
714.0,Noibat,40,30,35,45,40,55,245,Flying,Dragon,Frisk,Infiltrator,Telepathy,Purple,None
715.0,Noivern,85,70,80,97,80,123,535,Flying,Dragon,Frisk,Infiltrator,Telepathy,Purple,None

### NOT queries
There are two ways to do negation. Consider the following query for selecting all pokemon who are Fire type, but not Flying

```
query = ((pokedex_df['Type I']=='Fire') & ~(pokedex_df['Type II']=='Flying'))\
        | ((pokedex_df['Type I']!='Flying') & (pokedex_df['Type II']=='Fire'))
```

The first way to do negation is with the tilde ~ symbol, which negates the subsequent boolean statement:
We use this in `~(pokedex_df['Type II']=='Flying')`.
The parentheses determine order of operations. First we find all entries where their secondary type is "Flying"
Then the tilde in front negates that statement, flipping all True values to False, and vice versa

The second way to do negation is using the != notation, which represents "not equal to"
We use this in `(pokedex_df['Type I']!='Flying')`
This finds all entries where their primary type is not equal to "Flying"

In [72]:
query = ((pokedex_df['Type I']=='Fire') & ~(pokedex_df['Type II']=='Flying'))\
        | ((pokedex_df['Type I']!='Flying') & (pokedex_df['Type II']=='Fire'))

pokedex_df.loc[query]

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color,Nickname
Index,,,,,,,,,,,,,,,
4.0,Charmander,39,52,43,60,50,65,309,Fire,,Blaze,,Solar Power,Red,Abby
5.0,Charmeleon,58,64,58,80,65,80,405,Fire,,Blaze,,Solar Power,Red,None
39.0,Vulpix,38,41,40,50,65,65,299,Fire,,Flash Fire,,Drought,Brown,None
40.0,Ninetales,73,76,75,81,100,100,505,Fire,,Flash Fire,,Drought,Yellow,None
63.0,Growlithe,55,70,45,70,50,60,350,Fire,,Intimidate,Flash Fire,Justified,Brown,None
64.0,Arcanine,90,110,80,100,80,95,555,Fire,,Intimidate,Flash Fire,Justified,Brown,None
83.0,Ponyta,50,85,55,65,65,90,410,Fire,,Run Away,Flash Fire,Flame Body,Yellow,None
84.0,Rapidash,65,100,70,80,80,105,500,Fire,,Run Away,Flash Fire,Flame Body,Yellow,None
149.0,Magmar,65,95,57,100,85,93,495,Fire,,Flame Body,,Vital Spirit,Red,None
160.0,Flareon,65,130,60,95,110,65,525,Fire,,Flash Fire,,Guts,Red,None
186.0,Cyndaquil,39,52,43,60,50,65,309,Fire,,Blaze,,Flash Fire,Yellow,None
187.0,Quilava,58,64,58,80,65,80,405,Fire,,Blaze,,Flash Fire,Yellow,None
188.0,Typhlosion,78,84,78,109,85,100,534,Fire,,Blaze,,Flash Fire,Yellow,None
248.0,Slugma,40,40,40,70,40,20,250,Fire,,Magma Armor,Flame Body,Weak Armor,Red,None
249.0,Magcargo,50,50,120,80,80,30,410,Fire,Rock,Magma Armor,Flame Body,Weak Armor,Red,None
260.0,Houndour,45,60,30,80,50,65,330,Dark,Fire,Early Bird,Flash Fire,Unnerve,Black,None
261.0,Houndoom,75,90,50,110,80,95,500,Dark,Fire,Early Bird,Flash Fire,Unnerve,Black,None
148.0,Magby,45,75,37,70,55,83,365,Fire,,Flame Body,,Vital Spirit,Red,None
268.0,Entei,115,115,85,90,75,100,580,Fire,,Pressure,,Flash Fire,Brown,None
279.0,Torchic,45,60,40,70,50,45,310,Fire,,Blaze,,Speed Boost,Red,None
280.0,Combusken,60,85,60,85,60,55,405,Fire,Fighting,Blaze,,Speed Boost,Red,None
281.0,Blaziken,80,120,70,110,70,80,530,Fire,Fighting,Blaze,,Speed Boost,Red,None
349.0,Numel,60,60,40,65,45,35,305,Fire,Ground,Oblivious,Simple,Own Tempo,Yellow,None
350.0,Camerupt,70,100,70,105,75,40,460,Fire,Ground,Magma Armor,Solid Rock,Anger Point,Red,None
351.0,Torkoal,70,85,140,85,70,20,470,Fire,,White Smoke,,Shell Armor,Brown,None
419.0,Chimchar,44,58,44,58,44,61,309,Fire,,Blaze,,Iron Fist,Brown,None
420.0,Monferno,64,78,52,78,52,81,405,Fire,Fighting,Blaze,,Iron Fist,Brown,None
421.0,Infernape,76,104,71,104,71,108,534,Fire,Fighting,Blaze,,Iron Fist,Brown,None
150.0,Magmortar,75,95,67,125,95,83,540,Fire,,Flame Body,,Vital Spirit,Red,None
479.1,Rotom (Heat),50,65,107,105,107,86,520,Electric,Fire,Levitate,,,Red,None
485.0,Heatran,91,90,106,130,106,77,600,Fire,Steel,Flash Fire,,Flame Body,Brown,None
494.0,Victini,100,100,100,100,100,100,600,Psychic,Fire,Victory Star,,,Yellow,None
498.0,Tepig,65,63,45,45,45,45,308,Fire,,Blaze,,Thick Fat,Red,None
499.0,Pignite,90,93,55,70,55,55,418,Fire,Fighting,Blaze,,Thick Fat,Red,None
500.0,Emboar,110,123,65,100,65,65,528,Fire,Fighting,Blaze,,Reckless,Red,None
513.0,Pansear,50,53,48,53,48,64,316,Fire,,Gluttony,,Blaze,Red,None
514.0,Simisear,75,98,63,98,63,101,498,Fire,,Gluttony,,Blaze,Red,None
554.0,Darumaka,70,90,45,15,45,50,315,Fire,,Hustle,,Inner Focus,Red,None
555.0,Darmanitan,105,140,55,30,55,95,480,Fire,,Sheer Force,,Zen Mode,Red,None
555.1,Darmanitan (Z),105,30,105,140,105,55,540,Fire,Psychic,,,Zen Mode,Red,None
607.0,Litwick,50,30,55,65,55,20,275,Ghost,Fire,Flash Fire,Flame Body,Shadow Tag,White,None
608.0,Lampent,60,40,60,95,60,55,370,Ghost,Fire,Flash Fire,Flame Body,Shadow Tag,Black,None
609.0,Chandelure,60,55,90,145,90,80,520,Ghost,Fire,Flash Fire,Flame Body,Shadow Tag,Black,None
631.0,Heatmor,85,97,66,105,66,65,484,Fire,,Gluttony,Flash Fire,White Smoke,Red,None
636.0,Larvesta,55,85,55,50,55,60,360,Bug,Fire,Flame Body,,Swarm,White,None
637.0,Volcarona,85,60,65,135,105,100,550,Bug,Fire,Flame Body,,Swarm,White,None
643.0,Reshiram,100,120,100,150,120,90,680,Dragon,Fire,Turboblaze,,,White,None
653.0,Fennekin,40,45,40,62,60,60,307,Fire,,Blaze,,Magician,Red,None
654.0,Braixen,59,59,58,90,70,73,409,Fire,,Blaze,,Magician,Red,None
655.0,Delphox,75,69,72,114,100,104,534,Fire,Psychic,Blaze,,Magician,Red,None
667.0,Litleo,62,50,58,73,54,72,369,Fire,Normal,Rivalry,Unnerve,Moxie,Brown,None
668.0,Pyroar,86,68,72,109,66,106,507,Fire,Normal,Rivalry,Unnerve,Moxie,Brown,None
721.0,Volcanion,80,110,120,130,90,70,600,Fire,Water,Water Absorb,,,Brown,None
725.0,Litten,45,65,40,60,40,70,320,Fire,,Blaze,Intimidate,,Red,None
726.0,Torracat,65,85,50,80,50,90,420,Fire,,Blaze,Intimidate,,Red,None
727.0,Incineroar,95,115,90,80,90,60,530,Fire,Dark,Blaze,Intimidate,,Red,None
757.0,Salandit,48,44,40,71,40,77,320,Poison,Fire,Corrosion,Oblivious,Oblivious,Black,None
758.0,Salazzle,68,64,60,111,60,117,480,Poison,Fire,Corrosion,Oblivious,Oblivious,Black,None
776.0,Turtonator,60,78,135,91,85,36,485,Fire,Dragon,Shell Armor,,,Red,None

In [71]:
query = (pokedex_df['HP'] ==  pokedex_df['Atk']) & (pokedex_df['Atk'] == pokedex_df['Def'])
pokedex_df.loc[query]

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color,Nickname
Index,,,,,,,,,,,,,,,
66.0,Poliwhirl,65,65,65,50,50,90,385,Water,,Water Absorb,Damp,Swift Swim,Blue,None
156.0,Ditto,48,48,48,48,48,48,288,Normal,,Limber,,Imposter,Purple,None
182.0,Mew,100,100,100,100,100,100,600,Psychic,,Synchronize,,,Pink,None
220.0,Sunkern,30,30,30,30,30,30,180,Grass,,Chlorophyll,Solar Power,Early Bird,Yellow,None
228.0,Misdreavus,60,60,60,85,85,85,435,Ghost,,Levitate,,,Gray,None
248.0,Slugma,40,40,40,70,40,20,250,Fire,,Magma Armor,Flame Body,Weak Armor,Red,None
115.0,Tyrogue,35,35,35,35,35,35,210,Fighting,,Guts,Steadfast,Vital Spirit,Purple,None
275.0,Celebi,100,100,100,100,100,100,600,Psychic,Grass,Natural Cure,,,Green,None
312.0,Slakoth,60,60,60,35,35,30,280,Normal,,Truant,,,Brown,None
313.0,Vigoroth,80,80,80,55,55,90,440,Normal,,Vital Spirit,,,White,None
354.0,Spinda,60,60,60,60,60,60,360,Normal,,Own Tempo,Tangled Feet,Contrary,Brown,None
378.0,Castform,70,70,70,70,70,70,420,Normal,,Forecast,,,White,None
389.0,Snorunt,50,50,50,50,50,50,300,Ice,,Inner Focus,Ice Body,Moody,Gray,None
390.0,Glalie,80,80,80,80,80,80,480,Ice,,Inner Focus,Ice Body,Moody,Gray,None
414.0,Jirachi,100,100,100,100,100,100,600,Steel,Psychic,Serene Grace,,,Yellow,None
229.0,Mismagius,60,60,60,105,105,105,495,Ghost,,Levitate,,,Purple,None
489.0,Phione,80,80,80,80,80,80,480,Water,,Hydration,,,Blue,None
490.0,Manaphy,100,100,100,100,100,100,600,Water,,Hydration,,,Blue,None
492.0,Shaymin,100,100,100,100,100,100,600,Grass,,Natural Cure,,,Green,None
493.0,Arceus,120,120,120,120,120,120,720,Normal,,Multitype,,,Gray,None
494.0,Victini,100,100,100,100,100,100,600,Psychic,Fire,Victory Star,,,Yellow,None
605.0,Elgyem,55,55,55,85,55,30,335,Psychic,,Telepathy,Synchronize,Analytic,Blue,None
606.0,Beheeyem,75,75,75,125,95,40,485,Psychic,,Telepathy,Synchronize,Analytic,Brown,None
772.0,Type: Null,95,95,95,95,95,59,534,Normal,,Battle Armor,,,Gray,None
773.0,Silvally,95,95,95,95,95,95,570,Normal,,RKS System,,,Gray,None

## Sorting
Dataframes can be sorted by value

In [58]:
pokedex_df.sort_values('Pokemon', ascending=False) # Sort by name descending

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Index,,,,,,,,,,,,,,
718.0,Zygarde,108,100,121,81,95,95,600,Dragon,Ground,Aura Break,,,Green
634.0,Zweilous,72,85,70,65,70,58,420,Dark,Dragon,Hustle,,,Blue
44.0,Zubat,40,45,35,30,40,55,245,Poison,Flying,Inner Focus,,Infiltrator,Purple
570.0,Zorua,40,65,40,80,40,65,330,Dark,,Illusion,,,Gray
571.0,Zoroark,60,105,60,120,60,105,510,Dark,,Illusion,,,Gray
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
681.0,Aegislash,60,50,150,50,150,60,520,Steel,Ghost,Stance Change,,,Brown
617.0,Accelgor,80,70,40,100,60,145,495,Bug,,Hydration,Sticky Hold,Unburden,Red
388.0,Absol,65,130,60,75,60,75,465,Dark,,Pressure,Super Luck,Justified,White
69.0,Abra,25,20,15,105,55,90,310,Psychic,,Synchronize,Inner Focus,Magic Guard,Brown
478.0,Abomasnow,90,92,75,92,85,60,494,Ice,Grass,Snow Warning,,Soundproof,White

In [59]:
# You can sort by multiple columns
pokedex_df.sort_values(['Type I','Type II', 'Total'], ascending=False) # Sort by type combination, then stats descending

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Index,,,,,,,,,,,,,,
424.0,Empoleon,84,86,88,111,101,60,530,Water,Steel,Torrent,,Defiant,Blue
565.0,Carracosta,74,108,133,83,65,32,495,Water,Rock,Solid Rock,Sturdy,Swift Swim,Blue
398.0,Relicanth,100,90,130,45,65,55,485,Water,Rock,Swift Swim,Rock Head,Sturdy,Gray
253.0,Corsola,55,55,85,65,85,35,380,Water,Rock,Hustle,Natural Cure,Regenerator,Pink
564.0,Tirtouga,54,78,103,53,45,22,355,Water,Rock,Solid Rock,Sturdy,Swift Swim,Blue
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292.0,Cascoon,50,35,55,25,25,15,205,Bug,,Shed Skin,,,Purple
664.0,Scatterbug,38,35,40,27,25,35,200,Bug,,Shield Dust,Compound Eyes,Friend Guard,Black
10.0,Caterpie,45,30,35,20,20,45,195,Bug,,Shield Dust,,Run Away,Green
289.0,Wurmple,45,45,35,20,30,20,195,Bug,,Shield Dust,,Run Away,Red
430.0,Kricketot,37,25,41,25,41,25,194,Bug,,Shed Skin,,Run Away,Red

## Adding columns, rows, and changing values
You can add another column like:
```
dataframe['NewColumnName'] = value
```
`value` can be a single value, an array of the same size as the index of `dataframe`, a pandas `Series`, or a dictionary mapping `index: value` for entries in the dataframe index

In [60]:
pokedex_df['Nickname'] = None
pokedex_df

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color,Nickname
Index,,,,,,,,,,,,,,,
1.0,Bulbasaur,45,49,49,65,65,45,318,Grass,Poison,Overgrow,,Chlorophyll,Green,None
2.0,Ivysaur,60,62,63,80,80,60,405,Grass,Poison,Overgrow,,Chlorophyll,Green,None
3.0,Venusaur,80,82,83,100,100,80,525,Grass,Poison,Overgrow,,Chlorophyll,Green,None
4.0,Charmander,39,52,43,60,50,65,309,Fire,,Blaze,,Solar Power,Red,None
5.0,Charmeleon,58,64,58,80,65,80,405,Fire,,Blaze,,Solar Power,Red,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
798.0,Kartana,59,181,131,59,31,109,570,Grass,Steel,Beast Boost,,,White,None
799.0,Guzzlord,223,101,53,97,53,43,570,Dark,Dragon,Beast Boost,,,Black,None
800.0,Necrozma,97,107,101,127,89,79,600,Psychic,,Prism Armor,,,Black,None
801.0,Magearna,80,95,115,130,115,65,600,Steel,Fairy,Soul-Heart,,,Gray,None
802.0,Marshadow,90,125,80,90,90,125,600,Fighting,Ghost,Technician,,,Gray,None

In [61]:
# you can change the value of an entry using indexing and assignment =
pokedex_df.loc[4,'Nickname'] = 'Abby' # indexing using .loc[] pokedex entry 4, 'Nickname column'
pokedex_df.iloc[113,-1] = 'Terry' # indexing using .iloc[] 113rd row, last column
pokedex_df.iloc[[3,113],:]

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color,Nickname
Index,,,,,,,,,,,,,,,
4.0,Charmander,39,52,43,60,50,65,309,Fire,,Blaze,,Solar Power,Red,Abby
129.0,Tangela,65,55,115,100,40,60,435,Grass,,Chlorophyll,Leaf Guard,Regenerator,Blue,Terry

## Combining Dataframes
### Appending

Some of you may have noticed that the pokedex file only includes Generations 1-7 of pokemon. Let's add the pokemon from Gen 8. The file `pokedex_gen8.csv` contains the pokedex entries for all of the pokemon that show up in the 8th generation of games (Sword/Shield).

In [62]:
# you can add another dataframe on to the end using append()
gen8_pokedex_df = pd.read_csv('pokedex_gen8.csv') # create a dataframe with new entries

In [63]:
appended_pokedex_df = pokedex_df.append(gen8_pokedex_df, ignore_index=True, sort=False) # the sort=False keyword prevents the columns from being reordered alphabetically
appended_pokedex_df = appended_pokedex_df.fillna('').drop_duplicates() # some cleanup operations, replace NaN with emptry strings, and drop duplicate rows
appended_pokedex_df

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color,Nickname,Galar Pokedex Number,Weight_kg,Height_m,Weight_lbs,Height_ft,Cap_Rate,Egg_Steps,Classification
0,Bulbasaur,45,49,49,65,65,45,318,Grass,Poison,Overgrow,,Chlorophyll,Green,,,,,,,,,
1,Ivysaur,60,62,63,80,80,60,405,Grass,Poison,Overgrow,,Chlorophyll,Green,,,,,,,,,
2,Venusaur,80,82,83,100,100,80,525,Grass,Poison,Overgrow,,Chlorophyll,Green,,,,,,,,,
3,Charmander,39,52,43,60,50,65,309,Fire,,Blaze,,Solar Power,Red,Abby,,,,,,,,
4,Charmeleon,58,64,58,80,65,80,405,Fire,,Blaze,,Solar Power,Red,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1215,Drakloak,68,80,50,60,50,102,,dragon,ghost,Clear Body,Infiltrator,Cursed Body,,,396,11,1.4,24.3,4.583,45,10240,Caretaker Pokémon
1216,Dragapult,88,120,75,100,75,142,,dragon,ghost,Clear Body,Infiltrator,Cursed Body,,,397,50,3,110.2,9.833,45,10240,Stealth Pokémon
1217,Zacian,92,130,115,80,115,138,,fairy,,Intrepid Sword,,,,,398,110,2.8,242.5,9.167,10,30720,Warrior Pokémon
1218,Zamazenta,92,130,115,80,115,138,,fighting,,Dauntless Shield,,,,,399,210,2.9,463,9.5,10,30720,Warrior Pokémon
1219,Eternatus,140,85,95,145,95,130,,poison,dragon,Pressure,,,,,400,950,20,2094.4,65.583,255,30720,Gigantic Pokémon

However, you may notice that some pokemon show up twice in the combined dataframe, and since the entries in `gen8_pokedex_df` includes different columns, `remove_duplicates` does not see those entries as duplicates.

To remedy this, we can index both dataframes by the name of the pokemon and use the [`combine_first`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.combine_first.html#pandas.DataFrame.combine_first) function to fill in the null values of one dataframe with the corresponding values in the other.

In [75]:
gen8_pokedex_indexed_by_name = gen8_pokedex_df.reset_index().set_index('Pokemon')
combined_pokedex_df = pokedex_indexed_by_name.combine_first(gen8_pokedex_indexed_by_name)
combined_pokedex_df

,Ability I,Ability II,Atk,Cap_Rate,Classification,Color,Def,Egg_Steps,Galar Pokedex Number,HP,Height_ft,Height_m,Hidden Ability,Index,SpAtk,SpDef,Speed,Total,Type I,Type II,Weight_kg,Weight_lbs,index
Pokemon,,,,,,,,,,,,,,,,,,,,,,,
Abomasnow,Snow Warning,,92.0,60.0,Frosted Tree Pokémon,White,75.0,5120.0,97.0,90.0,7.250,2.2,Soundproof,478.0,92.0,85.0,60.0,494.0,Ice,Grass,135.5,298.7,96.0
Abra,Synchronize,Inner Focus,20.0,NaN,NaN,Brown,15.0,NaN,NaN,25.0,NaN,NaN,Magic Guard,69.0,105.0,55.0,90.0,310.0,Psychic,,NaN,NaN,NaN
Absol,Pressure,Super Luck,130.0,NaN,NaN,White,60.0,NaN,NaN,65.0,NaN,NaN,Justified,388.0,75.0,60.0,75.0,465.0,Dark,,NaN,NaN,NaN
Accelgor,Hydration,Sticky Hold,70.0,75.0,Shell Out Pokémon,Red,40.0,3840.0,276.0,80.0,2.583,0.8,Unburden,617.0,100.0,60.0,145.0,495.0,Bug,,25.3,55.8,275.0
Aegislash,Stance Change,,50.0,45.0,Royal Sword Pokémon,Brown,150.0,5120.0,332.0,60.0,5.583,1.7,,681.0,50.0,150.0,60.0,520.0,Steel,Ghost,53.0,116.8,331.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zoroark,Illusion,,105.0,NaN,NaN,Gray,60.0,NaN,NaN,60.0,NaN,NaN,,571.0,120.0,60.0,105.0,510.0,Dark,,NaN,NaN,NaN
Zorua,Illusion,,65.0,NaN,NaN,Gray,40.0,NaN,NaN,40.0,NaN,NaN,,570.0,80.0,40.0,65.0,330.0,Dark,,NaN,NaN,NaN
Zubat,Inner Focus,,45.0,NaN,NaN,Purple,35.0,NaN,NaN,40.0,NaN,NaN,Infiltrator,44.0,30.0,40.0,55.0,245.0,Poison,Flying,NaN,NaN,NaN
Zweilous,Hustle,,85.0,45.0,Hostile Pokémon,Blue,70.0,10240.0,387.0,72.0,4.583,1.4,,634.0,65.0,70.0,58.0,420.0,Dark,Dragon,50.0,110.2,386.0
Zygarde,Aura Break,,100.0,NaN,NaN,Green,121.0,NaN,NaN,108.0,NaN,NaN,,718.0,81.0,95.0,95.0,600.0,Dragon,Ground,NaN,NaN,NaN

### Merges and Joins
A more advanced way to join dataframes is using the `merge` or `join` operations.

For those who have worked with SQL-style databases before, you may be familiar with `merge` and `join` operations. They are done to combine two tables or dataframes which share values in certain columns. This allows us to look up entries in another dataframe using the values of our current dataframe.

In this example, we will use `merge` to get the stats for a team of pokemon. This dataframe will just contain the names and nicknames of the pokemon that we want on our team. After we perform a merge, we will get a dataframe with the respective statistics for the pokemon we've chosen.

In [65]:
# feel free to replace the names of pokemon with ones you want on your team
team_df = pd.DataFrame({'my pokemon':['Bulbasaur','Squirtle','Charmander', 'Malamar','Magnezone','Venusaur'],
                       'nickname':['leafygurl','h2woah','toaster','Mal','Mag','Ven']})

There are four merge/join types in `pandas`:
- (INNER) JOIN: Returns records that have matching values in both tables
- (LEFT) JOIN: Returns all records from the left table, and the matched records from the right table 
- (RIGHT) JOIN: Returns all records from the right table, and the matched records from the left table   
- (OUTER) JOIN: Returns all records when there is a match in either left or right table
    

 ![inner join illustration, venn diagram with intersection colored in, from w3schools sql lesson](https://www.w3schools.com/sql/img_innerjoin.gif)
  ![left join illustration, venn diagram with full left circle colored in, from w3schools sql lesson](https://www.w3schools.com/sql/img_leftjoin.gif)
  ![right join illustration, venn diagram with full right circle colored in, from w3schools sql lesson](https://www.w3schools.com/sql/img_rightjoin.gif)
  ![outer join illustration, venn diagram with union of two circles colored in, from w3schools sql lesson](https://www.w3schools.com/sql/img_fulljoin.gif)

The information that we need in order to perform a merge is:
- what dataframes to merge
- what kind of merge/join (inner/left/right/outer)
- what columns to merge on in each dataframe

Knowing this, let's look at the function signature of merge for a dataframe

In [66]:
# you can use the question mark symbol ? to examine the function signature

pokedex_df.merge?

Signature:
pokedex_df.merge(
    right,
    how='inner',
    on=None,
    left_on=None,
    right_on=None,
    left_index=False,
    right_index=False,
    sort=False,
    suffixes=('_x', '_y'),
    copy=True,
    indicator=False,
    validate=None,
) -> 'DataFrame'
Docstring:
Merge DataFrame or named Series objects with a database-style join.

The join is done on columns or indexes. If joining columns on
columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
on indexes or indexes on a column or columns, the index will be passed on.

Parameters
----------
right : DataFrame or named Series
    Object to merge with.
how : {'left', 'right', 'outer', 'inner'}, default 'inner'
    Type of merge to be performed.

    * left: use only keys from left frame, similar to a SQL left outer join;
      preserve key order.
    * right: use only keys from right frame, similar to a SQL right outer join;
      preserve key order.
    * outer: use union of keys from both frames, similar to a SQL full outer
      join; sort keys lexicographically.
    * inner: use intersection of keys from both frames, similar to a SQL inner
      join; preserve the order of the left keys.
on : label or list
    Column or index level names to join on. These must be found in both
    DataFrames. If `on` is None and not merging on indexes then this defaults
    to the intersection of the columns in both DataFrames.
left_on : label or list, or array-like
    Column or index level names to join on in the left DataFrame. Can also
    be an array or list of arrays of the length of the left DataFrame.
    These arrays are treated as if they are columns.
right_on : label or list, or array-like
    Column or index level names to join on in the right DataFrame. Can also
    be an array or list of arrays of the length of the right DataFrame.
    These arrays are treated as if they are columns.
left_index : bool, default False
    Use the index from the left DataFrame as the join key(s). If it is a
    MultiIndex, the number of keys in the other DataFrame (either the index
    or a number of columns) must match the number of levels.
right_index : bool, default False
    Use the index from the right DataFrame as the join key. Same caveats as
    left_index.
sort : bool, default False
    Sort the join keys lexicographically in the result DataFrame. If False,
    the order of the join keys depends on the join type (how keyword).
suffixes : tuple of (str, str), default ('_x', '_y')
    Suffix to apply to overlapping column names in the left and right
    side, respectively. To raise an exception on overlapping columns use
    (False, False).
copy : bool, default True
    If False, avoid copy if possible.
indicator : bool or str, default False
    If True, adds a column to output DataFrame called "_merge" with
    information on the source of each row.
    If string, column with information on source of each row will be added to
    output DataFrame, and column will be named value of string.
    Information column is Categorical-type and takes on a value of "left_only"
    for observations whose merge key only appears in 'left' DataFrame,
    "right_only" for observations whose merge key only appears in 'right'
    DataFrame, and "both" if the observation's merge key is found in both.

validate : str, optional
    If specified, checks if merge is of specified type.

    * "one_to_one" or "1:1": check if merge keys are unique in both
      left and right datasets.
    * "one_to_many" or "1:m": check if merge keys are unique in left
      dataset.
    * "many_to_one" or "m:1": check if merge keys are unique in right
      dataset.
    * "many_to_many" or "m:m": allowed, but does not result in checks.

    .. versionadded:: 0.21.0

Returns
-------
DataFrame
    A DataFrame of the two merged objects.

See Also
--------
merge_ordered : Merge with optional filling/interpolation.
merge_asof : Merge on nearest keys.
DataFrame.join : Similar method using indices.

Notes
-----
Support for specifying index levels as the `on`, `left_on`, and
`right_on` parameters was added in version 0.23.0
Support for merging named Series objects was added in version 0.24.0

Examples
--------

>>> df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
...                     'value': [1, 2, 3, 5]})
>>> df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
...                     'value': [5, 6, 7, 8]})
>>> df1
    lkey value
0   foo      1
1   bar      2
2   baz      3
3   foo      5
>>> df2
    rkey value
0   foo      5
1   bar      6
2   baz      7
3   foo      8

Merge df1 and df2 on the lkey and rkey columns. The value columns have
the default suffixes, _x and _y, appended.

>>> df1.merge(df2, left_on='lkey', right_on='rkey')
  lkey  value_x rkey  value_y
0  foo        1  foo        5
1  foo        1  foo        8
2  foo        5  foo        5
3  foo        5  foo        8
4  bar        2  bar        6
5  baz        3  baz        7

Merge DataFrames df1 and df2 with specified left and right suffixes
appended to any overlapping columns.

>>> df1.merge(df2, left_on='lkey', right_on='rkey',
...           suffixes=('_left', '_right'))
  lkey  value_left rkey  value_right
0  foo           1  foo            5
1  foo           1  foo            8
2  foo           5  foo            5
3  foo           5  foo            8
4  bar           2  bar            6
5  baz           3  baz            7

Merge DataFrames df1 and df2, but raise an exception if the DataFrames have
any overlapping columns.

>>> df1.merge(df2, left_on='lkey', right_on='rkey', suffixes=(False, False))
Traceback (most recent call last):
...
ValueError: columns overlap but no suffix specified:
    Index(['value'], dtype='object')
File:      /opt/conda/lib/python3.7/site-packages/pandas/core/frame.py
Type:      method

The answers to the following questions to get the team dataframe with stats are:

**what dataframes to merge?**
`team_df` and `combined_pokedex_df`
    
**what kind of merge/join (inner/left/right/outer)?**
inner or left 
    
**what columns to merge on in each dataframe**
for `team_df`, the column is `my pokemon`, for `combined_pokedex_df`, it is the index.

In [67]:
team_with_stats = team_df.merge(combined_pokedex_df, how='inner',
                               left_on='my pokemon', right_index=True)
team_with_stats

,my pokemon,nickname,Ability I,Ability II,Atk,Cap_Rate,Classification,Color,Def,Egg_Steps,Galar Pokedex Number,HP,Height_ft,Height_m,Hidden Ability,Index,SpAtk,SpDef,Speed,Total,Type I,Type II,Weight_kg,Weight_lbs,index
0,Bulbasaur,leafygurl,Overgrow,,49.0,NaN,NaN,Green,49.0,NaN,NaN,45.0,NaN,NaN,Chlorophyll,1.0,65.0,65.0,45.0,318.0,Grass,Poison,NaN,NaN,NaN
1,Squirtle,h2woah,Torrent,,48.0,NaN,NaN,Blue,65.0,NaN,NaN,44.0,NaN,NaN,Rain Dish,7.0,60.0,54.0,43.0,314.0,Water,,NaN,NaN,NaN
2,Charmander,toaster,Blaze,,52.0,45.0,Lizard Pokémon,Red,43.0,5120.0,378.0,39.0,2.000,0.6,Solar Power,4.0,60.0,50.0,65.0,309.0,Fire,,8.5,18.7,377.0
3,Malamar,Mal,Suction Cups,Contrary,92.0,80.0,Overturning Pokémon,Blue,88.0,5120.0,291.0,86.0,4.917,1.5,Infiltrator,687.0,68.0,75.0,73.0,482.0,Dark,Psychic,47.0,103.6,290.0
4,Magnezone,Mag,Magnet Pull,Sturdy,70.0,NaN,NaN,Gray,115.0,NaN,NaN,70.0,NaN,NaN,Analytic,90.0,130.0,90.0,60.0,535.0,Electric,Steel,NaN,NaN,NaN
5,Venusaur,Ven,Overgrow,,82.0,NaN,NaN,Green,83.0,NaN,NaN,80.0,NaN,NaN,Chlorophyll,3.0,100.0,100.0,80.0,525.0,Grass,Poison,NaN,NaN,NaN

In [68]:
# we can select specific columns from the dataframe
team_with_stats.loc[:,['my pokemon','nickname','Total']]

   my pokemon   nickname  Total
0   Bulbasaur  leafygurl  318.0
1    Squirtle     h2woah  314.0
2  Charmander    toaster  309.0
3     Malamar        Mal  482.0
4   Magnezone        Mag  535.0
5    Venusaur        Ven  525.0

### Exercise
Put together a team of pokemon by editing `team_df` and performing a `merge`. Remember that you can only have 6 pokemon on a team at once.

In [76]:
combined_pokemon_df.loc(combined_pokemon_df.reset_index()['Pokemon'].str.startswith('P'))

NameError: name 'combined_pokemon_df' is not defined

## Calculations and operations
There are various ways to do math to the dataframes

### Column operations
You can perform basic math element-wise between columns, such as addition, subtraction, multiplication, and division.

Note that the `gen8_pokedex_df` does not contain a `Total` stats column, so currently the gen8 pokemon have `NaN` in that column. We can fix that, because `Total` is generated as the sum of the respective `HP` `Atk` `Def` `SpAtk` `SpDef` and `Speed`. We can add the entire columns at once, without having to loop over each entry. Pandas supports vectorized operations behind the scenes.

In [77]:
# these are the entries missing 'Total' stats
combined_pokedex_df.loc[combined_pokedex_df['Total'].isnull()]

,Ability I,Ability II,Atk,Cap_Rate,Classification,Color,Def,Egg_Steps,Galar Pokedex Number,HP,Height_ft,Height_m,Hidden Ability,Index,SpAtk,SpDef,Speed,Total,Type I,Type II,Weight_kg,Weight_lbs,index
Pokemon,,,,,,,,,,,,,,,,,,,,,,,
Alcremie,Sweet Veil,NaN,60.0,100.0,Cream Pokémon,NaN,75.0,5120.0,186.0,65.0,1.000,0.3,Aroma Veil,NaN,110.0,121.0,64.0,NaN,fairy,NaN,0.5,1.1,185.0
Appletun,Ripen,Gluttony,85.0,45.0,Apple Nectar Pokémon,NaN,80.0,5120.0,207.0,110.0,1.333,0.4,Thick Fat,NaN,100.0,80.0,30.0,NaN,grass,dragon,13.0,28.7,206.0
Applin,Ripen,Gluttony,40.0,255.0,Apple Core Pokémon,NaN,80.0,5120.0,205.0,40.0,0.667,0.2,Bulletproof,NaN,40.0,40.0,20.0,NaN,grass,dragon,0.5,1.1,204.0
Arctovish,Water Absorb,Ice Body,90.0,45.0,Fossil Pokémon,NaN,100.0,8960.0,377.0,90.0,6.583,2.0,Slush Rush,NaN,80.0,90.0,55.0,NaN,water,ice,175.0,385.8,376.0
Arctozolt,Volt Absorb,Static,100.0,45.0,Fossil Pokémon,NaN,90.0,8960.0,375.0,90.0,7.583,2.3,Slush Rush,NaN,90.0,80.0,55.0,NaN,electric,ice,150.0,330.7,374.0
Arrokuda,Swift Swim,NaN,63.0,255.0,Rush Pokémon,NaN,40.0,5120.0,180.0,41.0,1.667,0.5,Propeller Tail,NaN,40.0,30.0,66.0,NaN,water,NaN,1.0,2.2,179.0
Barraskewda,Swift Swim,NaN,123.0,60.0,Skewer Pokémon,NaN,60.0,5120.0,181.0,61.0,4.250,1.3,Propeller Tail,NaN,60.0,50.0,136.0,NaN,water,NaN,30.0,66.1,180.0
Blipbug,Swarm,Compoundeyes,20.0,255.0,Larva Pokémon,NaN,20.0,3840.0,10.0,25.0,1.333,0.4,Telepathy,NaN,25.0,45.0,45.0,NaN,bug,NaN,8.0,17.6,9.0
Boltund,Strong Jaw,NaN,90.0,45.0,Dog Pokémon,NaN,60.0,5120.0,47.0,69.0,3.250,1.0,Competitive,NaN,90.0,60.0,121.0,NaN,electric,NaN,34.0,75.0,46.0
Carkol,Steam Engine,Flame Body,60.0,120.0,Coal Pokémon,NaN,90.0,3840.0,162.0,80.0,3.583,1.1,Flash Fire,NaN,60.0,70.0,50.0,NaN,rock,fire,78.0,172.0,161.0
Centiskorch,Flash Fire,White Smoke,115.0,75.0,Radiator Pokémon,NaN,65.0,5120.0,160.0,100.0,9.833,3.0,Flame Body,NaN,90.0,90.0,65.0,NaN,fire,bug,120.0,264.6,159.0
Chewtle,Strong Jaw,Shell Armor,64.0,255.0,Snapping Pokémon,NaN,50.0,5120.0,42.0,50.0,1.000,0.3,Swift Swim,NaN,38.0,38.0,44.0,NaN,water,NaN,8.5,18.7,41.0
Cinderace,Blaze,NaN,116.0,45.0,Striker Pokémon,NaN,75.0,5120.0,6.0,80.0,4.583,1.4,Libero,NaN,65.0,75.0,119.0,NaN,fire,NaN,33.0,72.8,5.0
Clobbopus,Limber,NaN,68.0,180.0,Tantrum Pokémon,NaN,60.0,6400.0,351.0,50.0,2.000,0.6,Technician,NaN,50.0,50.0,32.0,NaN,fighting,NaN,4.0,8.8,350.0
Coalossal,Steam Engine,Flame Body,80.0,45.0,Coal Pokémon,NaN,120.0,3840.0,163.0,110.0,9.167,2.8,Flash Fire,NaN,80.0,90.0,30.0,NaN,rock,fire,310.5,684.5,162.0
Copperajah,Sheer Force,NaN,130.0,90.0,Copperderm Pokémon,NaN,69.0,6400.0,303.0,122.0,9.833,3.0,Heavy Metal,NaN,80.0,69.0,30.0,NaN,steel,NaN,650.0,1433.0,302.0
Corviknight,Pressure,Unnerve,87.0,45.0,Raven Pokémon,NaN,105.0,3840.0,23.0,98.0,7.250,2.2,Mirror Armor,NaN,53.0,85.0,67.0,NaN,flying,steel,75.0,165.3,22.0
Corvisquire,Keen Eye,Unnerve,67.0,120.0,Raven Pokémon,NaN,55.0,3840.0,22.0,68.0,2.583,0.8,Big Pecks,NaN,43.0,55.0,77.0,NaN,flying,NaN,16.0,35.3,21.0
Cramorant,Gulp Missile,NaN,85.0,45.0,Gulp Pokémon,NaN,55.0,5120.0,309.0,70.0,2.583,0.8,NaN,NaN,85.0,95.0,85.0,NaN,flying,water,18.0,39.7,308.0
Cufant,Sheer Force,NaN,80.0,190.0,Copperderm Pokémon,NaN,49.0,6400.0,302.0,72.0,3.917,1.2,Heavy Metal,NaN,40.0,49.0,40.0,NaN,steel,NaN,100.0,220.5,301.0
Cursola,Weak Armor,NaN,95.0,30.0,Coral Pokémon,NaN,50.0,5120.0,237.0,60.0,3.250,1.0,Perish Body,NaN,145.0,130.0,30.0,NaN,ghost,NaN,0.4,0.9,236.0
Dottler,Swarm,Compoundeyes,35.0,120.0,Radome Pokémon,NaN,80.0,3840.0,11.0,50.0,1.333,0.4,Telepathy,NaN,50.0,90.0,30.0,NaN,bug,psychic,19.5,43.0,10.0
Dracovish,Water Absorb,Strong Jaw,90.0,45.0,Fossil Pokémon,NaN,100.0,8960.0,376.0,90.0,7.583,2.3,Sand Rush,NaN,70.0,80.0,75.0,NaN,water,dragon,215.0,474.0,375.0
Dracozolt,Volt Absorb,Hustle,100.0,45.0,Fossil Pokémon,NaN,90.0,8960.0,374.0,90.0,5.917,1.8,Sand Rush,NaN,80.0,70.0,75.0,NaN,electric,dragon,190.0,418.9,373.0
Dragapult,Clear Body,Infiltrator,120.0,45.0,Stealth Pokémon,NaN,75.0,10240.0,397.0,88.0,9.833,3.0,Cursed Body,NaN,100.0,75.0,142.0,NaN,dragon,ghost,50.0,110.2,396.0
Drakloak,Clear Body,Infiltrator,80.0,45.0,Caretaker Pokémon,NaN,50.0,10240.0,396.0,68.0,4.583,1.4,Cursed Body,NaN,60.0,50.0,102.0,NaN,dragon,ghost,11.0,24.3,395.0
Drednaw,Strong Jaw,Shell Armor,115.0,75.0,Bite Pokémon,NaN,90.0,5120.0,43.0,90.0,3.250,1.0,Swift Swim,NaN,48.0,68.0,74.0,NaN,water,rock,115.5,254.6,42.0
Dreepy,Clear Body,Infiltrator,60.0,45.0,Lingering Pokémon,NaN,30.0,10240.0,395.0,28.0,1.667,0.5,Cursed Body,NaN,40.0,30.0,82.0,NaN,dragon,ghost,2.0,4.4,394.0
Drizzile,Torrent,NaN,60.0,45.0,Water Lizard Pokémon,NaN,55.0,5120.0,8.0,65.0,2.333,0.7,Sniper,NaN,95.0,55.0,90.0,NaN,water,NaN,11.5,25.4,7.0
Dubwool,Fluffy,Steadfast,80.0,127.0,Sheep Pokémon,NaN,100.0,3840.0,35.0,72.0,4.250,1.3,Bulletproof,NaN,60.0,90.0,88.0,NaN,normal,NaN,43.0,94.8,34.0
Duraludon,Light Metal,Heavy Metal,95.0,45.0,Alloy Pokémon,NaN,115.0,7680.0,371.0,70.0,5.917,1.8,Stalwart,NaN,120.0,50.0,85.0,NaN,steel,dragon,40.0,88.2,370.0
Eiscue,Ice Face,NaN,80.0,60.0,Penguin Pokémon,NaN,110.0,6400.0,370.0,75.0,4.583,1.4,NaN,NaN,65.0,90.0,50.0,NaN,ice,NaN,89.0,196.2,369.0
Eldegoss,Cotton Down,Regenerator,50.0,75.0,Cotton Bloom Pokémon,NaN,90.0,5120.0,127.0,60.0,1.667,0.5,Effect Spore,NaN,80.0,120.0,60.0,NaN,grass,NaN,2.5,5.5,126.0
Eternatus,Pressure,NaN,85.0,255.0,Gigantic Pokémon,NaN,95.0,30720.0,400.0,140.0,65.583,20.0,NaN,NaN,145.0,95.0,130.0,NaN,poison,dragon,950.0,2094.4,399.0
Falinks,Battle Armor,NaN,100.0,45.0,Formation Pokémon,NaN,100.0,6400.0,345.0,65.0,9.833,3.0,Defiant,NaN,70.0,60.0,75.0,NaN,fighting,NaN,62.0,136.7,344.0
Farfetchd,Steadfast,NaN,95.0,45.0,Wild Duck Pokémon,NaN,55.0,5120.0,218.0,52.0,2.583,0.8,Scrappy,NaN,58.0,62.0,55.0,NaN,fighting,NaN,15.0,33.1,217.0
Flapple,Ripen,Gluttony,110.0,45.0,Apple Wing Pokémon,NaN,80.0,5120.0,206.0,70.0,1.000,0.3,Hustle,NaN,95.0,60.0,70.0,NaN,grass,dragon,1.0,2.2,205.0
Frosmoth,Shield Dust,NaN,65.0,75.0,Frost Moth Pokémon,NaN,60.0,5120.0,350.0,70.0,4.250,1.3,Ice Scales,NaN,125.0,90.0,65.0,NaN,ice,bug,42.0,92.6,349.0
Gossifleur,Cotton Down,Regenerator,40.0,190.0,Flowering Pokémon,NaN,60.0,5120.0,126.0,40.0,1.333,0.4,Effect Spore,NaN,40.0,60.0,10.0,NaN,grass,NaN,2.2,4.9,125.0
Grapploct,Limber,NaN,118.0,45.0,Jujitsu Pokémon,NaN,90.0,6400.0,352.0,80.0,5.250,1.6,Technician,NaN,70.0,80.0,42.0,NaN,fighting,NaN,39.0,86.0,351.0
Greedent,Cheek Pouch,NaN,95.0,90.0,Greedy Pokémon,NaN,95.0,5120.0,25.0,120.0,2.000,0.6,Gluttony,NaN,55.0,75.0,20.0,NaN,normal,NaN,6.0,13.2,24.0
Grimmsnarl,Prankster,Frisk,120.0,45.0,Bulk Up Pokémon,NaN,65.0,5120.0,240.0,95.0,4.917,1.5,Pickpocket,NaN,95.0,75.0,60.0,NaN,dark,fairy,61.0,134.5,239.0
Grookey,Overgrow,NaN,65.0,45.0,Chimp Pokémon,NaN,50.0,5120.0,1.0,50.0,1.000,0.3,Grassy Surge,NaN,40.0,40.0,65.0,NaN,grass,NaN,5.0,11.0,0.0
Hakamoo,Bulletproof,Soundproof,75.0,45.0,Scaly Pokémon,NaN,90.0,10240.0,393.0,55.0,3.917,1.2,Overcoat,NaN,65.0,70.0,65.0,NaN,dragon,fighting,47.0,103.6,392.0
Hatenna,Healer,Anticipation,30.0,235.0,Calm Pokémon,NaN,45.0,5120.0,241.0,42.0,1.333,0.4,Magic Bounce,NaN,56.0,53.0,39.0,NaN,psychic,NaN,3.4,7.5,240.0
Hatterene,Healer,Anticipation,90.0,45.0,Silent Pokémon,NaN,95.0,5120.0,243.0,57.0,6.917,2.1,Magic Bounce,NaN,136.0,103.0,29.0,NaN,psychic,fairy,5.1,11.2,242.0
Hattrem,Healer,Anticipation,40.0,120.0,Serene Pokémon,NaN,65.0,5120.0,242.0,57.0,2.000,0.6,Magic Bounce,NaN,86.0,73.0,49.0,NaN,psychic,NaN,4.8,10.6,241.0
Impidimp,Prankster,Frisk,45.0,255.0,Wily Pokémon,NaN,30.0,5120.0,238.0,45.0,1.333,0.4,Pickpocket,NaN,55.0,40.0,50.0,NaN,dark,fairy,5.5,12.1,237.0
Indeedee,Inner Focus,Synchronize,65.0,30.0,Emotion Pokémon,NaN,55.0,10240.0,337.0,60.0,2.917,0.9,Psychic Surge,NaN,105.0,95.0,95.0,NaN,psychic,normal,28.0,61.7,336.0
Inteleon,Torrent,NaN,85.0,45.0,Secret Agent Pokémon,NaN,65.0,5120.0,9.0,70.0,6.250,1.9,Sniper,NaN,125.0,65.0,120.0,NaN,water,NaN,45.2,99.6,8.0
Jangmoo,Bulletproof,Soundproof,55.0,45.0,Scaly Pokémon,NaN,65.0,10240.0,392.0,45.0,2.000,0.6,Overcoat,NaN,45.0,45.0,45.0,NaN,dragon,NaN,29.7,65.5,391.0
Kommoo,Bulletproof,Soundproof,110.0,45.0,Scaly Pokémon,NaN,125.0,10240.0,394.0,75.0,5.250,1.6,Overcoat,NaN,100.0,105.0,85.0,NaN,dragon,fighting,78.2,172.4,393.0
Milcery,Sweet Veil,NaN,40.0,200.0,Cream Pokémon,NaN,40.0,5120.0,185.0,45.0,0.667,0.2,Aroma Veil,NaN,50.0,61.0,34.0,NaN,fairy,NaN,0.3,0.7,184.0
MimeJr,Soundproof,Filter,25.0,145.0,Mime Pokémon,NaN,45.0,6400.0,364.0,20.0,2.000,0.6,Technician,NaN,70.0,90.0,60.0,NaN,psychic,fairy,13.0,28.7,363.0
Morgrem,Prankster,Frisk,60.0,120.0,Devious Pokémon,NaN,45.0,5120.0,239.0,65.0,2.583,0.8,Pickpocket,NaN,75.0,55.0,70.0,NaN,dark,fairy,12.5,27.6,238.0
Morpeko,Hunger Switch,NaN,95.0,180.0,Two-Sided Pokémon,NaN,58.0,2560.0,344.0,58.0,1.000,0.3,NaN,NaN,70.0,58.0,97.0,NaN,electric,dark,3.0,6.6,343.0
MrMime,Vital Spirit,Screen Cleaner,65.0,45.0,Barrier Pokémon,NaN,65.0,6400.0,365.0,50.0,4.250,1.3,Ice Body,NaN,90.0,90.0,100.0,NaN,ice,psychic,54.5,120.2,364.0
MrRime,Tangled Feet,Screen Cleaner,85.0,45.0,Comedian Pokémon,NaN,75.0,6400.0,366.0,80.0,4.917,1.5,Ice Body,NaN,110.0,100.0,70.0,NaN,ice,psychic,58.2,128.3,365.0
Nickit,Run Away,Unburden,28.0,255.0,Fox Pokémon,NaN,28.0,3840.0,29.0,40.0,2.000,0.6,Stakeout,NaN,47.0,52.0,50.0,NaN,dark,NaN,8.9,19.6,28.0
Obstagoon,Reckless,Guts,90.0,45.0,Blocking Pokémon,NaN,101.0,3840.0,33.0,93.0,5.250,1.6,Defiant,NaN,60.0,81.0,95.0,NaN,dark,normal,46.0,101.4,32.0
Orbeetle,Swarm,Frisk,45.0,45.0,Seven Spot Pokémon,NaN,110.0,3840.0,12.0,60.0,1.333,0.4,Telepathy,NaN,80.0,120.0,90.0,NaN,bug,psychic,40.8,89.9,11.0
Perrserker,Battle Armor,Tough Claws,110.0,90.0,Viking Pokémon,NaN,100.0,5120.0,183.0,70.0,2.583,0.8,Steely Spirit,NaN,50.0,60.0,50.0,NaN,steel,NaN,28.0,61.7,182.0
Pincurchin,Lightning Rod,NaN,101.0,75.0,Sea Urchin Pokémon,NaN,95.0,5120.0,353.0,48.0,1.000,0.3,Electric Surge,NaN,91.0,85.0,15.0,NaN,electric,NaN,1.0,2.2,352.0
Polteageist,Weak Armor,NaN,65.0,60.0,Black Tea Pokémon,NaN,65.0,5120.0,336.0,60.0,0.667,0.2,Cursed Body,NaN,134.0,114.0,70.0,NaN,ghost,NaN,0.4,0.9,335.0
Raboot,Blaze,NaN,86.0,45.0,Rabbit Pokémon,NaN,60.0,5120.0,5.0,65.0,2.000,0.6,Libero,NaN,55.0,60.0,94.0,NaN,fire,NaN,9.0,19.8,4.0
Rillaboom,Overgrow,NaN,125.0,45.0,Drummer Pokémon,NaN,90.0,5120.0,3.0,100.0,6.917,2.1,Grassy Surge,NaN,60.0,70.0,85.0,NaN,grass,NaN,90.0,198.4,2.0
Rolycoly,Steam Engine,Heatproof,40.0,255.0,Coal Pokémon,NaN,50.0,3840.0,161.0,30.0,1.000,0.3,Flash Fire,NaN,40.0,50.0,30.0,NaN,rock,NaN,12.0,26.5,160.0
Rookidee,Keen Eye,Unnerve,47.0,255.0,Tiny Bird Pokémon,NaN,35.0,3840.0,21.0,38.0,0.667,0.2,Big Pecks,NaN,33.0,35.0,57.0,NaN,flying,NaN,1.8,4.0,20.0
Runerigus,Wandering Spirit,NaN,95.0,90.0,Grudge Pokémon,NaN,145.0,6400.0,328.0,58.0,5.250,1.6,NaN,NaN,50.0,105.0,30.0,NaN,ground,ghost,66.6,146.8,327.0
Sandaconda,Sand Spit,Shed Skin,107.0,120.0,Sand Snake Pokémon,NaN,125.0,5120.0,313.0,72.0,12.500,3.8,Sand Veil,NaN,65.0,70.0,71.0,NaN,ground,NaN,65.5,144.4,312.0
Scorbunny,Blaze,NaN,71.0,45.0,Rabbit Pokémon,NaN,40.0,5120.0,4.0,50.0,1.000,0.3,Libero,NaN,40.0,40.0,69.0,NaN,fire,NaN,4.5,9.9,3.0
Silicobra,Sand Spit,Shed Skin,57.0,255.0,Sand Snake Pokémon,NaN,75.0,5120.0,312.0,52.0,7.250,2.2,Sand Veil,NaN,35.0,50.0,46.0,NaN,ground,NaN,7.6,16.8,311.0
Sinistea,Weak Armor,NaN,45.0,120.0,Black Tea Pokémon,NaN,45.0,5120.0,335.0,40.0,0.333,0.1,Cursed Body,NaN,74.0,54.0,50.0,NaN,ghost,NaN,0.2,0.4,334.0
Sirfetchd,Steadfast,NaN,135.0,45.0,Wild Duck Pokémon,NaN,95.0,5120.0,219.0,62.0,2.583,0.8,Scrappy,NaN,68.0,82.0,65.0,NaN,fighting,NaN,117.0,257.9,218.0
Sizzlipede,Flash Fire,White Smoke,65.0,190.0,Radiator Pokémon,NaN,45.0,5120.0,159.0,50.0,2.333,0.7,Flame Body,NaN,50.0,50.0,45.0,NaN,fire,bug,1.0,2.2,158.0
Skwovet,Cheek Pouch,NaN,55.0,255.0,Cheeky Pokémon,NaN,55.0,5120.0,24.0,70.0,1.000,0.3,Gluttony,NaN,35.0,35.0,25.0,NaN,normal,NaN,2.5,5.5,23.0
Snom,Shield Dust,NaN,25.0,190.0,Worm Pokémon,NaN,35.0,5120.0,349.0,30.0,1.000,0.3,Ice Scales,NaN,45.0,30.0,20.0,NaN,ice,bug,3.8,8.4,348.0
Sobble,Torrent,NaN,40.0,45.0,Water Lizard Pokémon,NaN,40.0,5120.0,7.0,50.0,1.000,0.3,Sniper,NaN,70.0,40.0,70.0,NaN,water,NaN,4.0,8.8,6.0
Stonjourner,Power Spot,NaN,125.0,60.0,Big Rock Pokémon,NaN,135.0,6400.0,369.0,100.0,8.167,2.5,NaN,NaN,20.0,20.0,70.0,NaN,rock,NaN,520.0,1146.4,368.0
Thievul,Run Away,Unburden,58.0,127.0,Fox Pokémon,NaN,58.0,3840.0,30.0,70.0,3.917,1.2,Stakeout,NaN,87.0,92.0,90.0,NaN,dark,NaN,19.9,43.9,29.0
Thwackey,Overgrow,NaN,85.0,45.0,Beat Pokémon,NaN,70.0,5120.0,2.0,70.0,2.333,0.7,Grassy Surge,NaN,55.0,60.0,80.0,NaN,grass,NaN,14.0,30.9,1.0
Toxel,Rattled,Static,38.0,75.0,Baby Pokémon,NaN,35.0,6400.0,310.0,40.0,1.333,0.4,Klutz,NaN,54.0,35.0,40.0,NaN,electric,poison,11.0,24.3,309.0
Toxtricity,Punk Rock,Plus,98.0,45.0,Punk Pokémon,NaN,70.0,6400.0,311.0,75.0,5.250,1.6,Technician,NaN,114.0,70.0,75.0,NaN,electric,poison,40.0,88.2,310.0
TypeNull,Battle Armor,NaN,95.0,3.0,Synthetic Pokémon,NaN,95.0,30720.0,381.0,95.0,6.250,1.9,NaN,NaN,95.0,95.0,59.0,NaN,normal,NaN,120.5,265.7,380.0
Wishiwashi,Schooling,NaN,20.0,60.0,Small Fry Pokémon,NaN,20.0,3840.0,155.0,45.0,0.667,0.2,NaN,NaN,25.0,25.0,40.0,NaN,water,NaN,0.3,0.7,154.0
Wooloo,Fluffy,Run Away,40.0,255.0,Sheep Pokémon,NaN,55.0,3840.0,34.0,42.0,2.000,0.6,Bulletproof,NaN,40.0,45.0,48.0,NaN,normal,NaN,6.0,13.2,33.0
Yamper,Ball Fetch,NaN,45.0,255.0,Puppy Pokémon,NaN,50.0,5120.0,46.0,59.0,1.000,0.3,Rattled,NaN,40.0,50.0,26.0,NaN,electric,NaN,13.5,29.8,45.0
Zacian,Intrepid Sword,NaN,130.0,10.0,Warrior Pokémon,NaN,115.0,30720.0,398.0,92.0,9.167,2.8,NaN,NaN,80.0,115.0,138.0,NaN,fairy,NaN,110.0,242.5,397.0
Zamazenta,Dauntless Shield,NaN,130.0,10.0,Warrior Pokémon,NaN,115.0,30720.0,399.0,92.0,9.500,2.9,NaN,NaN,80.0,115.0,138.0,NaN,fighting,NaN,210.0,463.0,398.0

In [78]:
combined_pokedex_df['Total'] = combined_pokedex_df['HP']\
                               + combined_pokedex_df['Atk']\
                               + combined_pokedex_df['Def']\
                               + combined_pokedex_df['SpAtk']\
                               + combined_pokedex_df['SpDef']\
                               + combined_pokedex_df['Speed']\

In [ ]:
pokedex_df['Total']/ pokedex_df['HP'] # computes the ratio between total stats and HP

### Universal functions
Universal functions can operate on entire dataframes or slices of dataframes. They return a dataframe copy with the same index as the original dataframe. Numpy universal functions can be applied to any numeric dataframe or slice.

In [ ]:
np.log(10)

In [ ]:
np.log(pokedex_df.loc[:,'HP':'Total'].astype(float), axis=0) # take natural log of all stats
# again, these functions operate on each element independently, and return a dataframe with the same index and size of input

### .apply()
You can apply an arbitrary function to each row or column using the `.apply()` function.

If you pass the name of a function (e.g. np.mean, or the name of any function you've written), you can apply it to either each column, or each row using `.apply()`

In [ ]:
pokedex_df.loc[:,'Atk':'Speed'].apply(np.mean) # applies the function np.mean() to each column

In [ ]:
pokedex_df.loc[:,'Atk':'Speed'].apply(np.mean, axis=1) # if you wanted to apply it to each row instead, use the argument axis=1

The above example is actually a bit unnecessary. There are several built-in functions in dataframes, including a `.mean()` which has the same functionality.

In [ ]:
pokedex_df.loc[:,'Atk':'Speed'].mean()

In [ ]:
pokedex_df.loc[:,'Atk':'Speed'].mean(axis=1) #applies per row

Most [descriptive statistics](https://pandas.pydata.org/pandas-docs/stable/reference/frame.html#computations-descriptive-stats) (median, mode, standard deviation, count, quantile, etc) have built-in functions. Where `.apply()` really shines, however, is for applying custom functions. 

To show that functionality, let's take a sidebar and talk about lambda functions.

#### Lambda functions
Sometimes you want to define a function, but you don't want to write the whole function declaration setup 
```
def functionname(inputs):
  ...
  return outputs
```

In those situations, you can write lambda (also known as anonymous) functions. The syntax for a lambda function is:

```
functionname = lambda x: operations_on_x
```

For example, if you wanted to write a function that squares the input, you could write:

In [ ]:
square_it = lambda x: x**2 # recall that ** is exponentiation in python, this function returns the square of the input
for num in range(10):
  print(square_it(num))

This is especially useful if some function takes another function as an argument, like panda's `.apply()`

The typical usage of `.apply()` is:

`dataframe_obj.apply(functionname)`, which calls `functionname` on each column of `dataframe_obj`

However, you can replace `functionname` with a lambda function. In this example, we use the following lambda function:

```lambda col: [np.min(col), np.max(col)]```

The word `col` represents the argument, and then to the right of the colon, we return a list with two elements: the minimum and maximum values of the column

In [79]:
stats_ranges = pokedex_df.loc[:,'HP':'Total'].apply(lambda col: [np.min(col), np.max(col)], axis=0)
print(stats_ranges)

HP         [1, 255]
Atk        [5, 181]
Def        [5, 230]
SpAtk     [10, 180]
SpDef     [20, 230]
Speed      [5, 180]
Total    [175, 720]
dtype: object

the above can be expanded into a dataframe:

In [80]:
pokedex_df.loc[:,'HP':'Total'].apply(lambda col: [np.min(col), np.mean(col), np.max(col)], result_type='expand')
# each respective row corresponds to the function applied to the column

,HP,Atk,Def,SpAtk,SpDef,Speed,Total
0,1.00000,5.000000,5.000000,10.000000,20.000000,5.000000,175.000000
1,68.60122,76.115854,71.919512,69.957317,70.370732,66.140244,423.104878
2,255.00000,181.000000,230.000000,180.000000,230.000000,180.000000,720.000000

In [103]:
# we can rename the rows to make it more interpretable. Also note the backslash \
# character allows a command to continue onto the next line, ignoring whitespace
pokedex_df.loc[:,'HP':'Total']\
          .apply(lambda col: [np.min(col), np.mean(col), np.max(col)], result_type='expand')\
          .rename({0:'min', 1:'mean', 2:'max'})

,HP,Atk,Def,SpAtk,SpDef,Speed,Total
min,1.00000,5.000000,5.000000,10.000000,20.000000,5.000000,175.000000
mean,68.60122,76.115854,71.919512,69.957317,70.370732,66.140244,423.104878
max,255.00000,181.000000,230.000000,180.000000,230.000000,180.000000,720.000000

### Groupby
Dataframes can be grouped by column values, and operations can be applied to each group

In [ ]:
# counts the number of pokemon of each type combination
pokedex_df.groupby(['Type I','Type II'])['Total'].count()

In [129]:
# gets the range of stats for each type combination
pokedex_df.groupby(['Type I','Type II'])['Total'].apply(lambda col: [np.min(col), np.max(col)])
pokedex_df

KeyError: 0

In [143]:
combined_pokedex_df.groupby(['Ability I','Type I'])[['Total'], ['Atk']].apply(lambda col: [np.min(col), np.max(col)])

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.

TypeError: unhashable type: 'list'

# Multi-level indexing
In this section, we'll cover some more advanced topics in pandas, including 
*   Multi-indexing
*   Pivot tables

We'll be introducing some more data to play with, based on state populations over time

In [35]:
state_populations_url = 'https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-population.csv'
state_abbrevs_url = 'https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-abbrevs.csv'
state_areas_url = 'https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-areas.csv'

state_areas = pd.read_csv(state_areas_url, index_col='state')
state_areas.head() # just print top 5 rows

            area (sq. mi)
state
Alabama             52423
Alaska             656425
Arizona            114006
Arkansas            53182
California         163707

In [36]:
state_abbrevs = pd.read_csv(state_abbrevs_url)
state_abbrevs.head()

        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

In [37]:
state_populations = pd.read_csv(state_populations_url) 
state_populations.head(10) #print first 10 rows

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0
5           AL    total  2011   4801627.0
6           AL    total  2009   4757938.0
7           AL  under18  2009   1134192.0
8           AL  under18  2013   1111481.0
9           AL    total  2013   4833722.0

In [38]:
state_populations.tail()

     state/region     ages  year   population
2539          USA    total  2010  309326295.0
2540          USA  under18  2011   73902222.0
2541          USA    total  2011  311582564.0
2542          USA  under18  2012   73708179.0
2543          USA    total  2012  313873685.0

Note that the state populations are just listed by abbreviations. It may be useful to include the state names as a column in a table. We have this information in the `state_abbrevs` table. We'd like to merge it with the population data.

The function `pd.merge()` merges two dataframes using set logic.

In [39]:
merged = pd.merge(state_populations, state_abbrevs, how='outer',
                 left_on='state/region', right_on='abbreviation')
# The arguments left_on and right_on specify what columns to join on. It looks for matching values in each dataframe
# and fills in the additional columns of the merged dataframe based on the matching data
# The 'how' argument specifies what kind of join. Outer means keep all entries even if one does not show up in the other
# conversely, 'inner' discards rows where a corresponding entry does not exist in the other
merged

     state/region     ages  year   population    state abbreviation
0              AL  under18  2012    1117489.0  Alabama           AL
1              AL    total  2012    4817528.0  Alabama           AL
2              AL  under18  2010    1130966.0  Alabama           AL
3              AL    total  2010    4785570.0  Alabama           AL
4              AL  under18  2011    1125763.0  Alabama           AL
...           ...      ...   ...          ...      ...          ...
2539          USA    total  2010  309326295.0      NaN          NaN
2540          USA  under18  2011   73902222.0      NaN          NaN
2541          USA    total  2011  311582564.0      NaN          NaN
2542          USA  under18  2012   73708179.0      NaN          NaN
2543          USA    total  2012  313873685.0      NaN          NaN

[2544 rows x 6 columns]

In [40]:
# we can also drop the unnecessary extra abbreviation column now
merged = merged.drop('abbreviation', axis=1) #drop from columns
merged.head()

  state/region     ages  year  population    state
0           AL  under18  2012   1117489.0  Alabama
1           AL    total  2012   4817528.0  Alabama
2           AL  under18  2010   1130966.0  Alabama
3           AL    total  2010   4785570.0  Alabama
4           AL  under18  2011   1125763.0  Alabama

In [41]:
# we can check if there were any missing values
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state            True
dtype: bool

In [42]:
# let's see where the issue is. What entries are missing population entries?
merged.loc[merged['population'].isnull()]

     state/region     ages  year  population state
2448           PR  under18  1990         NaN   NaN
2449           PR    total  1990         NaN   NaN
2450           PR    total  1991         NaN   NaN
2451           PR  under18  1991         NaN   NaN
2452           PR    total  1993         NaN   NaN
2453           PR  under18  1993         NaN   NaN
2454           PR  under18  1992         NaN   NaN
2455           PR    total  1992         NaN   NaN
2456           PR  under18  1994         NaN   NaN
2457           PR    total  1994         NaN   NaN
2458           PR    total  1995         NaN   NaN
2459           PR  under18  1995         NaN   NaN
2460           PR  under18  1996         NaN   NaN
2461           PR    total  1996         NaN   NaN
2462           PR  under18  1998         NaN   NaN
2463           PR    total  1998         NaN   NaN
2464           PR    total  1997         NaN   NaN
2465           PR  under18  1997         NaN   NaN
2466           PR    total  1999         NaN   NaN
2467           PR  under18  1999         NaN   NaN

In [43]:
# what about where there's no state entry?
merged.loc[merged['state'].isnull(), 'state/region']

2448     PR
2449     PR
2450     PR
2451     PR
2452     PR
2453     PR
2454     PR
2455     PR
2456     PR
2457     PR
2458     PR
2459     PR
2460     PR
2461     PR
2462     PR
2463     PR
2464     PR
2465     PR
2466     PR
2467     PR
2468     PR
2469     PR
2470     PR
2471     PR
2472     PR
2473     PR
2474     PR
2475     PR
2476     PR
2477     PR
2478     PR
2479     PR
2480     PR
2481     PR
2482     PR
2483     PR
2484     PR
2485     PR
2486     PR
2487     PR
2488     PR
2489     PR
2490     PR
2491     PR
2492     PR
2493     PR
2494     PR
2495     PR
2496    USA
2497    USA
2498    USA
2499    USA
2500    USA
2501    USA
2502    USA
2503    USA
2504    USA
2505    USA
2506    USA
2507    USA
2508    USA
2509    USA
2510    USA
2511    USA
2512    USA
2513    USA
2514    USA
2515    USA
2516    USA
2517    USA
2518    USA
2519    USA
2520    USA
2521    USA
2522    USA
2523    USA
2524    USA
2525    USA
2526    USA
2527    USA
2528    USA
2529    USA
2530    USA
2531    USA
2532    USA
2533    USA
2534    USA
2535    USA
2536    USA
2537    USA
2538    USA
2539    USA
2540    USA
2541    USA
2542    USA
2543    USA
Name: state/region, dtype: object

In [44]:
# more concicely, we can use .unique() to only see the unique values
merged.loc[merged['state'].isnull(), 'state/region'].unique()

array(['PR', 'USA'], dtype=object)

In [45]:
# We can fix this easily
merged.loc[merged['state/region'] == 'PR', 'state'] = 'Puerto Rico'
merged.loc[merged['state/region'] == 'USA', 'state'] = 'United States'
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state           False
dtype: bool

In [46]:
merged

     state/region     ages  year   population          state
0              AL  under18  2012    1117489.0        Alabama
1              AL    total  2012    4817528.0        Alabama
2              AL  under18  2010    1130966.0        Alabama
3              AL    total  2010    4785570.0        Alabama
4              AL  under18  2011    1125763.0        Alabama
...           ...      ...   ...          ...            ...
2539          USA    total  2010  309326295.0  United States
2540          USA  under18  2011   73902222.0  United States
2541          USA    total  2011  311582564.0  United States
2542          USA  under18  2012   73708179.0  United States
2543          USA    total  2012  313873685.0  United States

[2544 rows x 5 columns]

In [47]:
# now let's combine the data with the area data
final = pd.merge(merged, state_areas, on='state', how='left')
final.head()

  state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

3790399

In [49]:
# we can use the .query() syntax to search for specific data
data2010 = final.query("year == 2010 & ages == 'total'") # specify column name 
data2010.set_index('state', inplace=True) # equivalent to data2010 = data2010.set_index('state')
data2010.head()

           state/region   ages  year  population  area (sq. mi)
state
Alabama              AL  total  2010   4785570.0        52423.0
Alaska               AK  total  2010    713868.0       656425.0
Arizona              AZ  total  2010   6408790.0       114006.0
Arkansas             AR  total  2010   2922280.0        53182.0
California           CA  total  2010  37333601.0       163707.0

In [50]:
# Let's compute the density of each state and then sort by density
density = data2010['population'] / data2010['area (sq. mi)']
density.sort_values(ascending=False, inplace=True)
density

state
District of Columbia    8898.897059
Puerto Rico             1058.665149
New Jersey              1009.253268
Rhode Island             681.339159
Connecticut              645.600649
Massachusetts            621.815538
Maryland                 466.445797
Delaware                 460.445752
New York                 356.094135
Florida                  286.597129
Pennsylvania             275.966651
Ohio                     257.549634
California               228.051342
Illinois                 221.687472
Virginia                 187.622273
Indiana                  178.197831
North Carolina           177.617157
Georgia                  163.409902
Tennessee                150.825298
South Carolina           144.854594
New Hampshire            140.799273
Hawaii                   124.746707
Kentucky                 107.586994
Michigan                 102.015794
Washington                94.557817
Texas                     93.987655
Alabama                   91.287603
Louisiana                 87.676099
Wisconsin                 86.851900
Missouri                  86.015622
West Virginia             76.519582
Vermont                   65.085075
Mississippi               61.321530
Minnesota                 61.078373
Arizona                   56.214497
Arkansas                  54.948667
Iowa                      54.202751
Oklahoma                  53.778278
Colorado                  48.493718
Oregon                    39.001565
Maine                     37.509990
Kansas                    34.745266
Utah                      32.677188
Nevada                    24.448796
Nebraska                  23.654153
Idaho                     18.794338
New Mexico                16.982737
South Dakota              10.583512
North Dakota               9.537565
Montana                    6.736171
Wyoming                    5.768079
Alaska                     1.087509
United States                   NaN
dtype: float64

In [ ]:
density.tail()

### Exercises
Compute the total population of the entire united states, as well as its population density for each year.

Sort the states by population density.

What year saw the biggest change in population for the US as a whole?

Which states had the biggest percentage change in population in that year?

3790399

False

In [152]:
data = final.loc[(final['state/region']=='USA') & (final['ages'] == 'total')]
data = data.drop(columns=['ages', 'state','area (sq. mi)','state/region'])
data.reset_index(drop=True, inplace=True)
density = data2['population'] / state_areas.loc[:, 'area (sq. mi)'].sum()
data.insert(2, "Density", density, True)
data

    year   population    Density
0   1990  249622814.0  65.856606
1   1991  252980942.0  66.742562
2   1992  256514231.0  67.674731
3   1993  259918595.0  68.572885
4   1994  263125826.0  69.419031
5   1995  266278403.0  70.250758
6   1996  269394291.0  71.072806
7   1997  272646932.0  71.930932
8   1998  275854116.0  72.777065
9   2000  282162411.0  74.441348
10  1999  279040181.0  73.617627
11  2001  284968955.0  75.181783
12  2002  287625193.0  75.882564
13  2003  290107933.0  76.537571
14  2004  292805298.0  77.249202
15  2005  295516599.0  77.964510
16  2006  298379912.0  78.719922
17  2007  301231207.0  79.472163
18  2008  304093966.0  80.227429
19  2013  316128839.0  83.402523
20  2009  306771529.0  80.933835
21  2010  309326295.0  81.607845
22  2011  311582564.0  82.203104
23  2012  313873685.0  82.807558

In [153]:
state_areas.sum().values

array([3790399])

In [154]:
# total population
final.loc[(final['state/region']!='USA')&(final['ages']=='total')]\
     .groupby('year')['population'].sum()

year
1990    249622814.0
1991    252980942.0
1992    256514231.0
1993    259918595.0
1994    263125826.0
1995    266278403.0
1996    269394291.0
1997    272646932.0
1998    275854116.0
1999    279040181.0
2000    285973016.0
2001    288787729.0
2002    291448894.0
2003    293934028.0
2004    296632176.0
2005    299337961.0
2006    302185126.0
2007    305014202.0
2008    307854832.0
2009    310511939.0
2010    313047503.0
2011    315269144.0
2012    317525230.0
2013    319743925.0
Name: population, dtype: float64

In [155]:
final.query("state!='United States' & ages=='total'").groupby('year')['population'].sum()

year
1990    249622814.0
1991    252980942.0
1992    256514231.0
1993    259918595.0
1994    263125826.0
1995    266278403.0
1996    269394291.0
1997    272646932.0
1998    275854116.0
1999    279040181.0
2000    285973016.0
2001    288787729.0
2002    291448894.0
2003    293934028.0
2004    296632176.0
2005    299337961.0
2006    302185126.0
2007    305014202.0
2008    307854832.0
2009    310511939.0
2010    313047503.0
2011    315269144.0
2012    317525230.0
2013    319743925.0
Name: population, dtype: float64

In [156]:
final['density'] = final['population']/final['area (sq. mi)']
final.loc[(final['state']=='United States') & (final['ages']=='total')]

,state/region,ages,year,population,state,area (sq. mi),density
2497,USA,total,1990,249622814.0,United States,NaN,NaN
2498,USA,total,1991,252980942.0,United States,NaN,NaN
2501,USA,total,1992,256514231.0,United States,NaN,NaN
2502,USA,total,1993,259918595.0,United States,NaN,NaN
2505,USA,total,1994,263125826.0,United States,NaN,NaN
2508,USA,total,1995,266278403.0,United States,NaN,NaN
2509,USA,total,1996,269394291.0,United States,NaN,NaN
2510,USA,total,1997,272646932.0,United States,NaN,NaN
2513,USA,total,1998,275854116.0,United States,NaN,NaN
2515,USA,total,2000,282162411.0,United States,NaN,NaN
2517,USA,total,1999,279040181.0,United States,NaN,NaN
2518,USA,total,2001,284968955.0,United States,NaN,NaN
2520,USA,total,2002,287625193.0,United States,NaN,NaN
2522,USA,total,2003,290107933.0,United States,NaN,NaN
2524,USA,total,2004,292805298.0,United States,NaN,NaN
2526,USA,total,2005,295516599.0,United States,NaN,NaN
2528,USA,total,2006,298379912.0,United States,NaN,NaN
2530,USA,total,2007,301231207.0,United States,NaN,NaN
2532,USA,total,2008,304093966.0,United States,NaN,NaN
2535,USA,total,2013,316128839.0,United States,NaN,NaN
2536,USA,total,2009,306771529.0,United States,NaN,NaN
2539,USA,total,2010,309326295.0,United States,NaN,NaN
2541,USA,total,2011,311582564.0,United States,NaN,NaN
2543,USA,total,2012,313873685.0,United States,NaN,NaN

In [158]:
final.loc[final['state']=='United States','area (sq. mi)'] = state_areas.sum().values

In [159]:
final.loc[(final['state']=='United States') & (final['ages']=='total')]\
          .sort_values('year')['population'].diff()

2497          NaN
2498    3358128.0
2501    3533289.0
2502    3404364.0
2505    3207231.0
2508    3152577.0
2509    3115888.0
2510    3252641.0
2513    3207184.0
2517    3186065.0
2515    3122230.0
2518    2806544.0
2520    2656238.0
2522    2482740.0
2524    2697365.0
2526    2711301.0
2528    2863313.0
2530    2851295.0
2532    2862759.0
2536    2677563.0
2539    2554766.0
2541    2256269.0
2543    2291121.0
2535    2255154.0
Name: population, dtype: float64

In [160]:
idx_max = final.loc[(final['state']=='United States') & (final['ages']=='total')]\
          .sort_values('year')['population'].diff().idxmax()

In [161]:
year_max = final.loc[idx_max,'year']
year_max

1992

In [ ]:
data_year_max = final.loc[(final['year']==year_max)&(final['ages']=='total')]
data_year_before = final.loc[(final['year']==year_max-1)&(final['ages']=='total')]

In [ ]:
data_year_max = data_year_max.copy() # make a copy so we can change things destructively
data_year_max.loc[:,'percent_change'] = 100*(data_year_max['population'].values  - data_year_before['population'].values)/data_year_before['population'].values

In [ ]:
data_year_max

In [ ]:
data_year_max.loc[data_year_max['percent_change'].abs().idxmax()]

## Multiindexing
You can use multiple columns to define an index, as long as each row has a unique combination of values within those columns. In the following example, we will use the columns "state/region", "year", and "ages" of the population dataframe as an index

We use the `.set_index(['column_name1', 'column_name2, ...])'` command to create a multiindex from existing columns.

Note that many operations require a multiindex to be sorted, so we also call `.sort_index()` on the dataframe. Also, `.set_index()` and `.sort_index()` return a _copy_ of the dataframe, so we assign the output to itself to update the value.

In [162]:
# set index to use multiple columns
final = final.set_index(['state/region','year','ages']) # overwrite old version with new version with index set
final = final.sort_index() # replace itself with a version with a sorted index
final.tail(10) #print last 10 entries

                           population    state  area (sq. mi)   density
state/region year ages
WY           2009 total      559851.0  Wyoming        97818.0  5.723394
                  under18    134960.0  Wyoming        97818.0  1.379705
             2010 total      564222.0  Wyoming        97818.0  5.768079
                  under18    135351.0  Wyoming        97818.0  1.383702
             2011 total      567329.0  Wyoming        97818.0  5.799843
                  under18    135407.0  Wyoming        97818.0  1.384275
             2012 total      576626.0  Wyoming        97818.0  5.894886
                  under18    136526.0  Wyoming        97818.0  1.395714
             2013 total      582658.0  Wyoming        97818.0  5.956552
                  under18    137679.0  Wyoming        97818.0  1.407502

In [163]:
final.loc[('MA',2009,'total'):('WY',2011,'total')]

                           population          state  area (sq. mi)  \
state/region year ages
MA           2009 total     6517613.0  Massachusetts        10555.0
                  under18   1422935.0  Massachusetts        10555.0
             2010 total     6563263.0  Massachusetts        10555.0
                  under18   1415962.0  Massachusetts        10555.0
             2011 total     6606285.0  Massachusetts        10555.0
...                               ...            ...            ...
WY           2009 total      559851.0        Wyoming        97818.0
                  under18    134960.0        Wyoming        97818.0
             2010 total      564222.0        Wyoming        97818.0
                  under18    135351.0        Wyoming        97818.0
             2011 total      567329.0        Wyoming        97818.0

                              density
state/region year ages
MA           2009 total    617.490573
                  under18  134.811464
             2010 total    621.815538
                  under18  134.150829
             2011 total    625.891521
...                               ...
WY           2009 total      5.723394
                  under18    1.379705
             2010 total      5.768079
                  under18    1.383702
             2011 total      5.799843

[1589 rows x 4 columns]

### Stacking and unstacking
Columns can also have multiple levels. In fact, the columns can be thought of as just another index that runs horizontally. This is most easily illustrated by stacking, unstacking, and transposing.

You can convert a level of the row index to a column level using the `.unstack()` command. Conversely, `.stack()` moves a column level to the index

In [164]:
unstacked = final.unstack(level='ages') # you can unstack by level name; this moves the 'ages' categories into the column index
unstacked

                  population              state          area (sq. mi)  \
ages                   total   under18    total  under18         total
state/region year
AK           1990   553290.0  177502.0   Alaska   Alaska      656425.0
             1991   570193.0  182180.0   Alaska   Alaska      656425.0
             1992   588736.0  184878.0   Alaska   Alaska      656425.0
             1993   599434.0  187190.0   Alaska   Alaska      656425.0
             1994   603308.0  187439.0   Alaska   Alaska      656425.0
...                      ...       ...      ...      ...           ...
WY           2009   559851.0  134960.0  Wyoming  Wyoming       97818.0
             2010   564222.0  135351.0  Wyoming  Wyoming       97818.0
             2011   567329.0  135407.0  Wyoming  Wyoming       97818.0
             2012   576626.0  136526.0  Wyoming  Wyoming       97818.0
             2013   582658.0  137679.0  Wyoming  Wyoming       97818.0

                              density
ages                under18     total   under18
state/region year
AK           1990  656425.0  0.842884  0.270407
             1991  656425.0  0.868634  0.277534
             1992  656425.0  0.896882  0.281644
             1993  656425.0  0.913180  0.285166
             1994  656425.0  0.919081  0.285545
...                     ...       ...       ...
WY           2009   97818.0  5.723394  1.379705
             2010   97818.0  5.768079  1.383702
             2011   97818.0  5.799843  1.384275
             2012   97818.0  5.894886  1.395714
             2013   97818.0  5.956552  1.407502

[1272 rows x 8 columns]

In [166]:
restacked = unstacked.stack('ages', dropna=False) # stacks the column level back into the row index
# by default, .stack() omits entries with NaN. If you want to preserve the NaN entries, use the option dropna=False
restacked == final # just like the original state_populations dataframe

                           population  state  area (sq. mi)  density
state/region year ages
AK           1990 total          True   True           True     True
                  under18        True   True           True     True
             1991 total          True   True           True     True
                  under18        True   True           True     True
             1992 total          True   True           True     True
...                               ...    ...            ...      ...
WY           2011 under18        True   True           True     True
             2012 total          True   True           True     True
                  under18        True   True           True     True
             2013 total          True   True           True     True
                  under18        True   True           True     True

[2544 rows x 4 columns]

In [ ]:
final.unstack(level=0) # you can also unstack using integer levels. Here we unstacked level 0, corresponding to state/region

You can switch the row and column index using the transpose function `.T`

In [ ]:
final.unstack(level=0).T

### Pivoting
Pivoting is another advanced way to transform data. It creates a new dataframe using the values of columns as `index` and `column` values. 

You can then aggregate using `aggfunc` the elements of another column, which becomes the `values` of this new dataframe.

In [167]:
# let's create a table which lists all pokemon for given type combinations
pokedex_df.pivot_table(values='Pokemon', # line breaks within parentheses automatically continue onto next line
                       index='Type I', # values of Type I become index entries
                       columns='Type II', # likewise Type II become columns
                       aggfunc=lambda x:", ".join(x)).fillna('') # the lambda function here just joins a list of strings using a comma
                      # we also fill nan values with empty string for aesthetics

Type II,,Bug,Dark,Dragon,Electric,Fairy,Fighting,Fire,Flying,Ghost,Grass,Ground,Ice,Normal,Poison,Psychic,Rock,Steel,Water
Type I,,,,,,,,,,,,,,,,,,,
Bug,"Caterpie, Metapod, Pinsir, Pineco, Wurmple, Si...",,,,"Joltik, Galvantula, Charjabug, Vikavolt","Cutiefly, Ribombee","Heracross, Buzzwole, Pheromosa","Larvesta, Volcarona","Butterfree, Scyther, Ledyba, Ledian, Yanma, Be...",Shedinja,"Paras, Parasect, Wormadam (P), Sewaddle, Swadl...","Nincada, Wormadam (S)",,,"Weedle, Kakuna, Beedrill, Venonat, Venomoth, S...",,"Shuckle, Dwebble, Crustle","Forretress, Scizor, Wormadam (T), Escavalier, ...","Surskit, Wimpod, Golisopod"
Dark,"Umbreon, Poochyena, Mightyena, Absol, Darkrai,...",,,"Deino, Zweilous, Hydreigon, Guzzlord",,,"Scraggy, Scrafty","Houndour, Houndoom","Murkrow, Honchkrow, Vullaby, Mandibuzz, Yveltal",Sableye,,,"Sneasel, Weavile",,,"Inkay, Malamar",,"Pawniard, Bisharp",
Dragon,"Dratini, Dragonair, Bagon, Shelgon, Axew, Frax...",,,,Zekrom,,"Hakamo-o, Kommo-o",Reshiram,"Dragonite, Altaria, Salamence, Rayquaza",,,"Gible, Gabite, Garchomp, Zygarde",Kyurem,,,"Latias, Latios",,,
Electric,"Pikachu, Raichu, Voltorb, Electrode, Electabuz...",,,,,"Dedenne, Tapu Koko",,Rotom (Heat),"Zapdos, Rotom (Spin), Emolga, Thundurus",Rotom,Rotom (Cut),,Rotom (Frost),"Helioptile, Heliolisk",,,,"Magnemite, Magneton, Magnezone, Togedemaru",Rotom (Wash)
Fairy,"Clefairy, Clefable, Cleffa, Togepi, Snubbull, ...",,,,,,,,"Togetic, Togekiss",,,,,,,,,,
Fighting,"Mankey, Primeape, Machop, Machoke, Machamp, Hi...",,Pangoro,,,,,,Hawlucha,Marshadow,,,Crabominable,,,"Meditite, Medicham",,Lucario,
Fire,"Charmander, Charmeleon, Vulpix, Ninetales, Gro...",,Incineroar,Turtonator,,,"Combusken, Blaziken, Monferno, Infernape, Pign...",,"Charizard, Moltres, Ho-oh, Fletchinder, Talonf...",,,"Numel, Camerupt",,"Litleo, Pyroar",,"Darmanitan (Z), Delphox",Magcargo,Heatran,Volcanion
Flying,Tornadus,,,"Noibat, Noivern",,,,,,,,,,,,,,,
Ghost,"Misdreavus, Shuppet, Banette, Duskull, Dusclop...",,Spiritomb,"Giratina, Giratina (O)",,Mimikyu,,"Litwick, Lampent, Chandelure","Drifloon, Drifblim",,"Phantump, Trevenant, Pumpkaboo, Gourgeist, Dhe...","Sandygast, Palossand",,,"Gastly, Haunter, Gengar",,,,
Grass,"Tangela, Chikorita, Bayleef, Meganium, Belloss...",,"Nuzleaf, Shiftry, Cacturne",,,"Cottonee, Whimsicott, Morelull, Shiinotic, Tap...","Breloom, Virizion, Chesnaught",,"Hoppip, Skiploom, Jumpluff, Tropius, Shaymin (...",Decidueye,,Torterra,,,"Bulbasaur, Ivysaur, Venusaur, Oddish, Gloom, V...","Exeggcute, Exeggutor",,"Ferroseed, Ferrothorn, Kartana",
Ground,"Sandshrew, Sandslash, Diglett, Dugtrio, Cubone...",,"Sandile, Krokorok, Krookodile","Vibrava, Flygon",Stunfisk,,,,"Gligar, Gliscor, Landorus","Golett, Golurk",,,,,,"Baltoy, Claydol","Rhyhorn, Rhydon, Rhyperior",Excadrill,
Ice,"Snorunt, Glalie, Regice, Glaceon, Vanillite, V...",,,,,,,,"Articuno, Delibird",Froslass,"Snover, Abomasnow","Swinub, Piloswine, Mamoswine",,,,"Jynx, Smoochum",,,"Spheal, Sealeo, Walrein"
Normal,"Rattata, Raticate, Meowth, Persian, Lickitung,...",,,Drampa,,"Jigglypuff, Wigglytuff, Igglybuff, Azurill","Meloetta (P), Stufful, Bewear",,"Pidgey, Pidgeotto, Pidgeot, Spearow, Fearow, F...",,"Deerling, Sawsbuck",Diggersby,,,,"Girafarig, Meloetta (A), Oranguru",,,Bibarel
Poison,"Ekans, Arbok, Nidoran♀, Nidorina, Nidoran♂, Ni...",Skorupi,"Stunky, Skuntank, Drapion",Dragalge,,,"Croagunk, Toxicroak","Salandit, Salazzle","Zubat, Golbat, Crobat",,,"Nidoqueen, Nidoking",,,,,,,"Skrelp, Mareanie, Toxapex"
Psychic,"Abra, Kadabra, Alakazam, Drowzee, Hypno, Mewtw...",,Hoopa (U),,,"Mr. Mime, Ralts, Kirlia, Gardevoir, Mime Jr., ...",Gallade,Victini,"Natu, Xatu, Lugia, Woobat, Swoobat, Sigilyph","Hoopa (C), Lunala",Celebi,,,,,,,Solgaleo,
Rock,"Sudowoodo, Nosepass, Regirock, Cranidos, Rampa...","Anorith, Armaldo",Tyranitar,"Tyrunt, Tyrantrum",,"Carbink, Diancie",Terrakion,,"Aerodactyl, Archen, Archeops, Minior (meteor),...",,"Lileep, Cradily","Geodude, Graveler, Golem, Onix, Larvitar, Pupitar","Amaura, Aurorus",,Nihilego,"Lunatone, Solrock",,"Shieldon, Bastiodon, Probopass","Omanyte, Omastar, Kabuto, Kabutops, Binacle, B..."
Steel,"Registeel, Klink, Klang, Klinklang",,,Dialga,,"Mawile, Klefki, Magearna",Cobalion,,"Skarmory, Celesteela","Honedge, Doublade, Aegislash",,Steelix,,,,"Beldum, Metang, Metagross, Jirachi, Bronzor, B...","Aron, Lairon, Aggron",,
Water,"Squirtle, Wartortle, Blastoise, Psyduck, Goldu...","Dewpider, Araquanid","Carvanha, Sharpedo, Crawdaunt, Greninja","Kingdra, Palkia","Chinchou, Lanturn","Marill, Azumarill, Primarina, Tapu Fini","Poliwrath, Keldeo",,"Gyarados, Mantine, Wingull, Pelipper, Mantyke,...","Frillish, Jellicent","Lotad, Lombre, Ludicolo","Wooper, Quagsire, Marshtomp, Swampert, Barboac...","Dewgong, Cloyster, Lapras",,"Tentacool, Tentacruel, Qwilfish","Slowpoke, Slowbro, Starmie, Slowking, Bruxish","Corsola, Relicanth, Tirtouga, Carracosta",Empoleon,

In [168]:
# compute the average stats for each type combination
pokedex_df.unstack()
pokedex_df.pivot_table(values='Total',
                       index='Type I', 
                       columns='Type II', 
                       aggfunc=lambda x: np.mean(x)).fillna('')

Type II,,Bug,Dark,Dragon,Electric,Fairy,Fighting,Fire,Flying,Ghost,Grass,Ground,Ice,Normal,Poison,Psychic,Rock,Steel,Water
Type I,,,,,,,,,,,,,,,,,,,
Bug,290.277778,,,,422.75,384,546.667,455,404.077,236,382.333,345,,,332.273,,435,494.667,343
Dark,421.888889,,,472.5,,,418,415,494,380,,,470,,,385,,415,
Dragon,403.916667,,,,680,,510,680,592.5,,,477.5,660,,,600,,,
Electric,411.888889,,,,,500.5,,520,527,440,520,,520,385,,,,440,520
Fairy,409.312500,,,,,,,,475,,,,,,,,,,
Fighting,396.681818,,495,,,,,,500,600,,,478,,,345,,525,
Fire,409.400000,,530,485,,,470,,525.167,,,382.5,,438,,537,410,600,600
Flying,580.000000,,,390,,,,,,,,,,,,,,,
Ghost,415.666667,,485,680,,476,,388.333,423,,425.8,400,,,405,,,,
Grass,396.236842,,431.667,,,404,523.333,,405.714,530,,525,,,396.857,422.5,,454.667,
Ground,401.533333,,384,430,471,,,,513.333,393,,,,,,400,455,508,
Ice,434.416667,,,,,,,,455,480,414,410,,,,380,,,410
Normal,408.538462,,,485,,273.75,480,,362.423,,405,423,,,,515,,,410
Poison,379.600000,330,436,494,,,395,400,411.667,,,495,,,,,,,373.333
Psychic,447.552632,,680,,,389,518,600,449.667,640,600,,,,,,,680,
Rock,410.750000,425,600,441.5,,550,580,,484.6,,425,378.333,441.5,,570,440,,456.667,417.667
Steel,460.000000,,,680,,483.333,580,,517.5,431,,510,,,,453.333,430,,
Water,402.516129,361.5,440.75,610,395,440,540,,404,407.5,346.667,410.444,510,,426.667,458,428.75,530,

In [169]:
# You can compute multiple aggregations on multiple columns by passing a dict
# into the aggfunc argument: aggfunc={'column_name':[list_of_function_names]}
# Note that in this case, the 'value' argument is ignored
pokedex_df.pivot_table(index='Type I', 
                       columns='Type II', 
                       aggfunc={'Total':[lambda x: np.mean(x),lambda x: np.std(x)], 
                                'Atk':[lambda x: np.mean(x),lambda x: np.std(x)]}).fillna('')

                 Atk                                                           \
          <lambda_0>
Type II               Bug     Dark Dragon Electric    Fairy Fighting     Fire
Type I
Bug        51.000000                            69       50  133.667     72.5
Dark       82.000000                   89                       82.5       75
Dragon     89.083333                           150              92.5      120
Electric   69.740741                                   86.5                65
Fairy      63.000000
Fighting   97.454545           124
Fire       78.200000           115     78                      100.5
Flying    115.000000                   50
Ghost      66.666667            92    110                90           41.6667
Grass      68.973684            95                     60.8      109
Ground     90.933333       90.3333     85       66
Ice        72.166667
Normal     74.615385                   60             41.25  109.333
Poison     72.266667   50       82     75                       83.5       54
Psychic    62.763158           160                  46.6667      125      100
Rock      102.083333  110      134    105                75      129
Steel      77.500000                  120           86.6667       90
Water      69.806452   55   106.25  107.5       48    54.75     78.5

                                                                              \

Type II    Flying  Ghost    Grass   Ground      Ice Normal   Poison  Psychic
Type I
Bug       63.6154     90  73.8333       62                  59.0909
Dark         92.2     75                      107.5                       73
Dragon     122.25                     97.5      130                       85
Electric    86.25     50       65                65   46.5
Fairy          45
Fighting       92    125                        132                       50
Fire      89.6667                       80              59              49.5
Flying
Ghost          65            92.4       65                       50
Grass     62.2857    107               109                  68.4286     67.5
Ground    98.3333     99                                                  55
Ice            70     80       77  93.3333                                40
Normal    74.7308              80       56                           72.3333
Poison    71.6667                       87
Psychic      62.5  111.5      100
Rock        103.4              61  79.6667       68              53       75
Steel        90.5     80                85                           79.6667
Water     56.5714     50       50       76  81.6667         68.3333       79

                                                                              \
                                    <lambda_1>
Type II      Rock    Steel    Water            Bug     Dark  Dragon Electric
Type I
Bug       56.6667  108.833  63.3333  26.576932                       13.3978
Dark                   105           24.331050               15.748
Dragon                               27.369260                             0
Electric             65.75       65  25.174344
Fairy                                29.178331
Fighting               110           24.959471            0
Fire           50       90      110  25.110954            0       0
Flying                                0.000000                   20
Ghost                                25.712081            0      10
Grass              108.333           24.264428      18.7083
Ground    118.333      135           27.073891      19.2931      15        0
Ice                              60  22.737023
Normal                           85  30.579879                    0
Poison                      58.6667  19.020924   0  13.4907       0
Psychic                137           36.258889            0
Rock               49.6667  75.3333  31.322139  15        0      16
Steel          90                    16.007811                    0
Water       82.75       86           24.718961  15  13.8632    12.5       10

                   ...      Total                                              \
                   ... <lambda_0>
Type II     Fairy  ...     Normal   Poison  Psychic    Rock    Steel    Water
Type I             ...
Bug             5  ...             332.273              435  494.667      343
Dark               ...                          385              415
Dragon             ...                          600
Electric     28.5  ...        385                                440      520
Fairy              ...
Fighting           ...                          345              525
Fire               ...        438               537     410      600      600
Flying             ...
Ghost           0  ...                 405
Grass     37.1074  ...             396.857    422.5          454.667
Ground             ...                          400     455      508
Ice                ...                          380                       410
Normal    18.8331  ...                          515                       410
Poison             ...                                                373.333
Psychic   21.9216  ...                                           680
Rock           25  ...                 570      440          456.667  417.667
Steel      6.2361  ...                      453.333     430
Water     22.4207  ...             426.667      458  428.75      530

                                                                         \
          <lambda_1>
Type II                Bug     Dark   Dragon Electric    Fairy Fighting
Type I
Bug       102.044547                          70.1334       80  32.9983
Dark      116.244421                 120.701                         70
Dragon     98.592138                                0                90
Electric  104.400345                                      69.5
Fairy     120.241797
Fighting   90.478720              0
Fire       95.351840              0        0                    60.8468
Flying      0.000000                     145
Ghost      86.963594              0        0                 0
Grass     107.069194        64.8503                    112.134  49.2161
Ground    107.571289        91.6115       90        0
Ice       101.313423
Normal    114.215865                       0           92.1531  107.083
Poison     81.638880     0  76.1446        0                         95
Psychic   123.480810              0                    135.084        0
Rock       95.928033    70        0     79.5                50        0
Steel     104.880885                       0           90.3081        0
Water     105.745700  92.5  82.9258       70       65  124.499       40

                                                                       \

Type II      Fire   Flying    Ghost    Grass   Ground      Ice Normal
Type I
Bug            95  76.3216        0  68.9847       79
Dark           85  107.954        0                         40
Dragon          0  67.5925                    128.525        0
Electric        0  62.1852        0        0                 0     96
Fairy                   70
Fighting                 0        0                          0
Fire               91.8847                       77.5              69
Flying
Ghost     100.857       75           86.2309       80
Grass               106.08        0                 0
Ground             69.4422       90
Ice                    125        0       80  117.757
Normal             85.7197                70        0
Poison         80  122.293                          0
Psychic         0  123.284       40        0
Rock                58.188                70  64.3342     79.5
Steel                 52.5  80.5109                 0
Water              91.7232     72.5  106.249   98.386  25.4951



Type II    Poison  Psychic     Rock    Steel    Water
Type I
Bug       91.0385           78.7401  53.4031  133.184
Dark                    97                75
Dragon                   0
Electric                             75.6637        0
Fairy
Fighting                65                 0
Fire                     3        0        0        0
Flying
Ghost     77.5672
Grass     81.2042     97.5           110.876
Ground                 100  80.4156        0
Ice                     75                    97.9796
Normal             61.7792                          0
Poison                                         86.249
Psychic                                    0
Rock            0        0           76.4126   80.688
Steel              124.722  81.6497
Water     73.5225  72.9794  61.9854        0

[18 rows x 76 columns]

# Exercise
Using this data (or any other data you're interested in and you find online), put together an analysis using pandas that investigates an interesting question.

It can be serious or silly. Like "Do states with higher population density tend to vote democratic?" (you'd need to pull additional data for this) or "Do pokemon whose names start with the letter D have better stats than those who start with F?"

We'll ask some volunteers to present their analysis at the end